apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: 2018-11-13T05:48:02Z
  creationTimestamp: null
  generation: 2
  labels:
    app: gogs
  name: gogs
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: The Gogs git server docker image
      tags: gogs,go,golang
      version: 0.11.4
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/cicd/gogs:0.11.4
    generation: 2
    importPolicy: {}
    name: 0.11.4
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
