apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: 2018-11-22T10:17:53Z
  creationTimestamp: null
  generation: 2
  labels:
    app: tomcat
  name: tomcat
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/generated-by: OpenShiftWebConsole
      openshift.io/imported-from: tomcat:latest
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/cicd/tomcat:latest
    generation: 2
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
