apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    description: Defines how to deploy the glusterblock provisioner pod.
  creationTimestamp: null
  generation: 1
  labels:
    glusterblock: storage-provisioner-dc
    glusterfs: block-storage-provisioner-dc
  name: glusterblock-storage-provisioner-dc
spec:
  replicas: 1
  selector:
    glusterfs: block-storage-provisioner-pod
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        glusterfs: block-storage-provisioner-pod
      name: glusterblock-provisioner
    spec:
      containers:
      - env:
        - name: PROVISIONER_NAME
          value: gluster.org/glusterblock
        image: rhgs3/rhgs-gluster-block-prov-rhel7:latest
        imagePullPolicy: IfNotPresent
        name: glusterblock-provisioner
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: glusterblock-storage-provisioner
      serviceAccountName: glusterblock-storage-provisioner
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
