apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    openshift.io/image.dockerRepositoryCheck: 2018-11-13T08:56:04Z
  creationTimestamp: null
  generation: 2
  labels:
    app: sonarqube
  name: sonarqube
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: The SonarQube Docker image
      tags: sonarqube
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/devpipeline/sonarqube:6.7
    generation: 2
    importPolicy: {}
    name: "6.7"
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
