apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "1936"
    prometheus.io/scrape: "true"
    prometheus.openshift.io/password: ecsGVZrzfk
    prometheus.openshift.io/username: admin
    service.alpha.openshift.io/serving-cert-generation-error: secret/router-certs
      references serviceUID , which does not match 73ae7bdf-e7f8-11e8-b832-0aa0c5b29fe8
    service.alpha.openshift.io/serving-cert-generation-error-num: "10"
    service.alpha.openshift.io/serving-cert-secret-name: router-certs
  creationTimestamp: null
  labels:
    router: router
  name: router
spec:
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  - name: 443-tcp
    port: 443
    protocol: TCP
    targetPort: 443
  - name: 1936-tcp
    port: 1936
    protocol: TCP
    targetPort: 1936
  selector:
    router: router
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
