apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    glusterfs: heketi-storage-service
    heketi: storage-service
  name: heketi-storage
subsets:
- addresses:
  - ip: 10.128.0.129
    nodeName: amos01-master001.amosdemo.io
    targetRef:
      kind: Pod
      name: heketi-storage-2-k9xgh
      namespace: glusterfs
      resourceVersion: "5380867"
      uid: ebb45cf4-ecb5-11e8-ba2b-0aa0c5b29fe8
  ports:
  - name: heketi
    port: 8080
    protocol: TCP
