apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  name: heketi-db-storage-endpoints
subsets:
- addresses:
  - ip: 172.31.128.209
  - ip: 172.31.16.234
  - ip: 172.31.96.90
  ports:
  - port: 1
    protocol: TCP
