apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    app: jenkins-ephemeral
    template: jenkins-ephemeral-template
  name: jenkins
subsets:
- addresses:
  - ip: 10.129.0.53
    nodeName: amos01-infra001.amosdemo.io
    targetRef:
      kind: Pod
      name: jenkins-1-n8lp5
      namespace: glusterfs
      resourceVersion: "2922975"
      uid: f2216ac2-ebc9-11e8-ba2b-0aa0c5b29fe8
  ports:
  - name: web
    port: 8080
    protocol: TCP
