apiVersion: v1
kind: Route
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
    openshift.io/host.generated: "true"
  creationTimestamp: null
  labels:
    app: testphpapplication
  name: testphpapplication
spec:
  host: testphpapplication-achaitanya1.apps01.amosdemo.io
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: testphpapplication
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: 2018-11-22T09:21:35Z
      status: "True"
      type: Admitted
    host: testphpapplication-achaitanya1.apps01.amosdemo.io
    routerName: router
    wildcardPolicy: None
