apiVersion: v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: testphpapplication
  name: testapplicationroute
spec:
  host: chaitanya.apps01.amosdemo.io
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
  to:
    kind: Service
    name: testphpapplication
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: 2018-11-22T09:24:05Z
      status: "True"
      type: Admitted
    host: chaitanya.apps01.amosdemo.io
    routerName: router
    wildcardPolicy: None
