apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    app: eap70-postgresql-persistent-s2i
    application: myapp
    template: eap70-postgresql-persistent-s2i
    xpaas: 1.4.14
  name: myapp
spec:
  replicas: 1
  selector:
    deploymentConfig: myapp
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        application: myapp
        deploymentConfig: myapp
      name: myapp
    spec:
      containers:
      - env:
        - name: DB_SERVICE_PREFIX_MAPPING
          value: myapp-postgresql=DB
        - name: DB_JNDI
          value: java:jboss/datasources/TodoListDS
        - name: DB_USERNAME
          value: userki1
        - name: DB_PASSWORD
          value: dLGLDSaR
        - name: DB_DATABASE
          value: root
        - name: TX_DATABASE_PREFIX_MAPPING
          value: myapp-postgresql=DB
        - name: DB_MIN_POOL_SIZE
        - name: DB_MAX_POOL_SIZE
        - name: DB_TX_ISOLATION
        - name: JGROUPS_PING_PROTOCOL
          value: openshift.DNS_PING
        - name: OPENSHIFT_DNS_PING_SERVICE_NAME
          value: myapp-ping
        - name: OPENSHIFT_DNS_PING_SERVICE_PORT
          value: "8888"
        - name: HTTPS_KEYSTORE_DIR
          value: /etc/eap-secret-volume
        - name: HTTPS_KEYSTORE
          value: keystore.jks
        - name: HTTPS_KEYSTORE_TYPE
        - name: HTTPS_NAME
        - name: HTTPS_PASSWORD
        - name: MQ_CLUSTER_PASSWORD
          value: s4YRwaL0
        - name: MQ_QUEUES
        - name: MQ_TOPICS
        - name: JGROUPS_ENCRYPT_SECRET
          value: eap7-app-secret
        - name: JGROUPS_ENCRYPT_KEYSTORE_DIR
          value: /etc/jgroups-encrypt-secret-volume
        - name: JGROUPS_ENCRYPT_KEYSTORE
          value: jgroups.jceks
        - name: JGROUPS_ENCRYPT_NAME
        - name: JGROUPS_ENCRYPT_PASSWORD
        - name: JGROUPS_CLUSTER_PASSWORD
          value: 5OWwatKM
        - name: AUTO_DEPLOY_EXPLODED
          value: "false"
        - name: DEFAULT_JOB_REPOSITORY
          value: myapp-postgresql
        - name: TIMER_SERVICE_DATA_STORE
          value: myapp-postgresql
        image: docker-registry.default.svc:5000/develop/myapp@sha256:30ccf9b6f9e789d10765d3535ab868d08136fdd7c32b6d22e9ad21c3f326bd75
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /opt/eap/bin/livenessProbe.sh
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: myapp
        ports:
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        - containerPort: 8888
          name: ping
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /opt/eap/bin/readinessProbe.sh
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/eap-secret-volume
          name: eap-keystore-volume
          readOnly: true
        - mountPath: /etc/jgroups-encrypt-secret-volume
          name: eap-jgroups-keystore-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 75
      volumes:
      - name: eap-keystore-volume
        secret:
          defaultMode: 420
          secretName: eap7-app-secret
      - name: eap-jgroups-keystore-volume
        secret:
          defaultMode: 420
          secretName: eap7-app-secret
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - myapp
      from:
        kind: ImageStreamTag
        name: myapp:latest
        namespace: develop
    type: ImageChange
  - type: ConfigChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
