apiVersion: v1
kind: Route
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
    openshift.io/host.generated: "true"
  creationTimestamp: null
  labels:
    app: php
  name: php
spec:
  host: php-devpipeline.apps01.amosdemo.io
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: php
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: 2018-11-13T10:24:31Z
      status: "True"
      type: Admitted
    host: php-devpipeline.apps01.amosdemo.io
    routerName: router
    wildcardPolicy: None
