apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  creationTimestamp: null
  labels:
    build: tomcat1
  name: tomcat1
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: tomcat1:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: tomcat:latest
        namespace: cicd
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: ho-vp08c2mqgWOmYm_kC
    type: GitHub
  - generic:
      secret: f1ufFnAhVZGyObd3Cwte
    type: Generic
status:
  lastVersion: 0
