apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    app: dancer-mysql-example
    template: dancer-mysql-example
  name: database
subsets:
- addresses:
  - ip: 10.131.0.143
    nodeName: amos01-compute001.amosdemo.io
    targetRef:
      kind: Pod
      name: database-1-xqps2
      namespace: dddmo
      resourceVersion: "5641531"
      uid: 4c5f344d-f793-11e8-ba2b-0aa0c5b29fe8
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
