apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    docker-registry: default
  name: docker-registry
subsets:
- addresses:
  - ip: 10.129.0.33
    nodeName: amos01-infra001.amosdemo.io
    targetRef:
      kind: Pod
      name: docker-registry-1-snpjb
      namespace: default
      resourceVersion: "289500"
      uid: e676c36d-dda0-11e8-b362-0aa0c5b29fe8
  ports:
  - name: 5000-tcp
    port: 5000
    protocol: TCP
