apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    gluster.kubernetes.io/provisioned-for-pvc: metrics-cassandra-1
  name: glusterfs-dynamic-metrics-cassandra-1
spec:
  ports:
  - port: 1
    protocol: TCP
    targetPort: 1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
