apiVersion: v1
kind: Project
metadata:
  annotations:
    openshift.io/description: poc-fuse-springboot-demo-v2
    openshift.io/display-name: poc-fuse-springboot-demo-v2
    openshift.io/requester: admin
    openshift.io/sa.scc.mcs: s0:c13,c12
    openshift.io/sa.scc.supplemental-groups: 1000180000/10000
    openshift.io/sa.scc.uid-range: 1000180000/10000
  creationTimestamp: null
  name: poc-fuse-springboot-demo-v2
spec:
  finalizers:
  - openshift.io/origin
  - kubernetes
status:
  phase: Active
