apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: logging-es-data-master-llgd3fuk
    openshift.io/deployment.name: logging-es-data-master-llgd3fuk-1
    openshift.io/scc: restricted
  creationTimestamp: null
  generateName: logging-es-data-master-llgd3fuk-1-
  labels:
    component: es
    deployment: logging-es-data-master-llgd3fuk-1
    deploymentconfig: logging-es-data-master-llgd3fuk
    logging-infra: elasticsearch
    provider: openshift
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: logging-es-data-master-llgd3fuk-1
    uid: 613d88b6-ee40-11e8-ba2b-0aa0c5b29fe8
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: logging-infra
              operator: In
              values:
              - elasticsearch
          topologyKey: kubernetes.io/hostname
        weight: 100
  containers:
  - env:
    - name: DC_NAME
      value: logging-es-data-master-llgd3fuk
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: KUBERNETES_TRUST_CERT
      value: "true"
    - name: SERVICE_DNS
      value: logging-es-cluster
    - name: CLUSTER_NAME
      value: logging-es
    - name: INSTANCE_RAM
      value: 8Gi
    - name: HEAP_DUMP_LOCATION
      value: /elasticsearch/persistent/heapdump.hprof
    - name: NODE_QUORUM
      value: "1"
    - name: RECOVER_EXPECTED_NODES
      value: "1"
    - name: RECOVER_AFTER_TIME
      value: 5m
    - name: READINESS_PROBE_TIMEOUT
      value: "30"
    - name: POD_LABEL
      value: component=es
    - name: IS_MASTER
      value: "true"
    - name: HAS_DATA
      value: "true"
    - name: PROMETHEUS_USER
      value: system:serviceaccount:openshift-metrics:prometheus
    image: registry.access.redhat.com/openshift3/logging-elasticsearch:v3.9.27
    imagePullPolicy: IfNotPresent
    name: elasticsearch
    ports:
    - containerPort: 9200
      name: restapi
      protocol: TCP
    - containerPort: 9300
      name: cluster
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - /usr/share/java/elasticsearch/probe/readiness.sh
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 30
    resources:
      limits:
        memory: 8Gi
      requests:
        cpu: "1"
        memory: 8Gi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/elasticsearch/secret
      name: elasticsearch
      readOnly: true
    - mountPath: /usr/share/java/elasticsearch/config
      name: elasticsearch-config
      readOnly: true
    - mountPath: /elasticsearch/ani
      name: elasticsearch-storage
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: aggregated-logging-elasticsearch-token-wbqvt
      readOnly: true
  - args:
    - --upstream-ca=/etc/elasticsearch/secret/admin-ca
    - --https-address=:4443
    - -provider=openshift
    - -client-id=system:serviceaccount:logging:aggregated-logging-elasticsearch
    - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
    - -cookie-secret=ODFtcmxGa1RkTXdKQTAwZQ==
    - -basic-auth-password=P4AAxTGqLBOzPiLS
    - -upstream=https://localhost:9200
    - '-openshift-sar={"namespace": "logging", "verb": "view", "resource": "prometheus",
      "group": "metrics.openshift.io"}'
    - '-openshift-delegate-urls={"/": {"resource": "prometheus", "verb": "view", "group":
      "metrics.openshift.io", "namespace": "logging"}}'
    - --tls-cert=/etc/tls/private/tls.crt
    - --tls-key=/etc/tls/private/tls.key
    - -pass-access-token
    - -pass-user-headers
    image: registry.access.redhat.com/openshift3/oauth-proxy:v3.9.27
    imagePullPolicy: IfNotPresent
    name: proxy
    ports:
    - containerPort: 4443
      name: proxy
      protocol: TCP
    resources:
      limits:
        memory: 64Mi
      requests:
        cpu: 100m
        memory: 64Mi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/tls/private
      name: proxy-tls
      readOnly: true
    - mountPath: /etc/elasticsearch/secret
      name: elasticsearch
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: aggregated-logging-elasticsearch-token-wbqvt
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: aggregated-logging-elasticsearch-dockercfg-qlmgt
  nodeName: amos01-master001.amosdemo.io
  nodeSelector:
    region: master
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    seLinuxOptions:
      level: s0:c21,c10
    supplementalGroups:
    - 65534
  serviceAccount: aggregated-logging-elasticsearch
  serviceAccountName: aggregated-logging-elasticsearch
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: proxy-tls
    secret:
      defaultMode: 420
      secretName: prometheus-tls
  - name: elasticsearch
    secret:
      defaultMode: 420
      secretName: logging-elasticsearch
  - configMap:
      defaultMode: 420
      name: logging-elasticsearch
    name: elasticsearch-config
  - name: elasticsearch-storage
    persistentVolumeClaim:
      claimName: logging-es-0
  - name: aggregated-logging-elasticsearch-token-wbqvt
    secret:
      defaultMode: 420
      secretName: aggregated-logging-elasticsearch-token-wbqvt
status:
  phase: Pending
  qosClass: Burstable
