apiVersion: v1
kind: Route
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
    openshift.io/host.generated: "true"
  creationTimestamp: null
  labels:
    app: django-ex
  name: django-ex
spec:
  host: django-ex-abcd.apps01.amosdemo.io
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: django-ex
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: 2018-11-29T09:39:22Z
      status: "True"
      type: Admitted
    host: django-ex-abcd.apps01.amosdemo.io
    routerName: router
    wildcardPolicy: None
