apiVersion: v1
kind: Route
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
    openshift.io/host.generated: "true"
  creationTimestamp: null
  labels:
    app: ruby-ex
  name: ruby-ex
spec:
  host: ruby-ex-abcd.apps01.amosdemo.io
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: ruby-ex
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: 2018-11-30T11:40:21Z
      status: "True"
      type: Admitted
    host: ruby-ex-abcd.apps01.amosdemo.io
    routerName: router
    wildcardPolicy: None
