apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/deployment-config.latest-version: "2"
    openshift.io/deployment-config.name: testphpapplication
    openshift.io/deployment.name: testphpapplication-2
    openshift.io/scc: anyuid
  creationTimestamp: null
  generateName: testphpapplication-2-
  labels:
    app: testphpapplication
    deployment: testphpapplication-2
    deploymentconfig: testphpapplication
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: testphpapplication-2
    uid: 4278e6a5-ee38-11e8-ba2b-0aa0c5b29fe8
spec:
  containers:
  - image: docker-registry.default.svc:5000/achaitanya1/testphpapplication@sha256:999f787cb60fe0f5dd59d85f831d354450c92acb0743f5d6e1543dff1eb57173
    imagePullPolicy: Always
    name: testphpapplication
    ports:
    - containerPort: 8080
      protocol: TCP
    - containerPort: 8443
      protocol: TCP
    resources: {}
    securityContext:
      capabilities:
        drop:
        - MKNOD
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-lx9z5
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: default-dockercfg-qbtsg
  nodeName: amos01-compute001.amosdemo.io
  nodeSelector:
    node-role.kubernetes.io/compute: "true"
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    seLinuxOptions:
      level: s0:c21,c15
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: default-token-lx9z5
    secret:
      defaultMode: 420
      secretName: default-token-lx9z5
status:
  phase: Pending
  qosClass: BestEffort
