apiVersion: v1
host: amos01-master001.amosdemo.io
hostIP: 172.31.96.187
kind: HostSubnet
metadata:
  annotations:
    pod.network.openshift.io/node-uid: d2782150-dd9a-11e8-b362-0aa0c5b29fe8
  creationTimestamp: null
  name: amos01-master001.amosdemo.io
subnet: 10.128.0.0/23
