apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    openshift.io/deployer-pod.completed-at: 2018-11-19 10:41:59 +0000 UTC
    openshift.io/deployer-pod.created-at: 2018-11-19 10:42:04 +0000 UTC
    openshift.io/deployer-pod.name: cakephp-mysql-persistent-2-deploy
    openshift.io/deployment-config.latest-version: "2"
    openshift.io/deployment-config.name: cakephp-mysql-persistent
    openshift.io/deployment.phase: Complete
    openshift.io/deployment.replicas: "1"
    openshift.io/deployment.status-reason: image change
    openshift.io/encoded-deployment-config: |
      {"kind":"DeploymentConfig","apiVersion":"v1","metadata":{"name":"cakephp-mysql-persistent","namespace":"cloud-test","selfLink":"/apis/apps.openshift.io/v1/namespaces/cloud-test/deploymentconfigs/cakephp-mysql-persistent","uid":"718d8164-ebe7-11e8-ba2b-0aa0c5b29fe8","resourceVersion":"2961562","generation":3,"creationTimestamp":"2018-11-19T10:39:50Z","labels":{"app":"cakephp-mysql-persistent","template":"cakephp-mysql-persistent"},"annotations":{"description":"Defines how to deploy the application server","template.alpha.openshift.io/wait-for-ready":"true"}},"spec":{"strategy":{"type":"Recreate","recreateParams":{"timeoutSeconds":600,"pre":{"failurePolicy":"Retry","execNewPod":{"command":["./migrate-database.sh"],"containerName":"cakephp-mysql-persistent"}}},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["cakephp-mysql-persistent"],"from":{"kind":"ImageStreamTag","namespace":"cloud-test","name":"cakephp-mysql-persistent:latest"},"lastTriggeredImage":"docker-registry.default.svc:5000/cloud-test/cakephp-mysql-persistent@sha256:4b81316236687c001a2c1afa2b2b4b7db412dca8264c378217700946509d0fef"}},{"type":"ConfigChange"}],"replicas":1,"test":false,"selector":{"name":"cakephp-mysql-persistent"},"template":{"metadata":{"name":"cakephp-mysql-persistent","creationTimestamp":null,"labels":{"name":"cakephp-mysql-persistent"}},"spec":{"containers":[{"name":"cakephp-mysql-persistent","image":"docker-registry.default.svc:5000/cloud-test/cakephp-mysql-persistent@sha256:4b81316236687c001a2c1afa2b2b4b7db412dca8264c378217700946509d0fef","ports":[{"containerPort":8080,"protocol":"TCP"}],"env":[{"name":"DATABASE_SERVICE_NAME","value":"mysql"},{"name":"DATABASE_ENGINE","value":"mysql"},{"name":"DATABASE_NAME","value":"default"},{"name":"DATABASE_USER","valueFrom":{"secretKeyRef":{"name":"cakephp-mysql-persistent","key":"database-user"}}},{"name":"DATABASE_PASSWORD","valueFrom":{"secretKeyRef":{"name":"cakephp-mysql-persistent","key":"database-password"}}},{"name":"CAKEPHP_SECRET_TOKEN","valueFrom":{"secretKeyRef":{"name":"cakephp-mysql-persistent","key":"cakephp-secret-token"}}},{"name":"CAKEPHP_SECURITY_SALT","valueFrom":{"secretKeyRef":{"name":"cakephp-mysql-persistent","key":"cakephp-security-salt"}}},{"name":"CAKEPHP_SECURITY_CIPHER_SEED","valueFrom":{"secretKeyRef":{"name":"cakephp-mysql-persistent","key":"cakephp-security-cipher-seed"}}},{"name":"OPCACHE_REVALIDATE_FREQ","value":"2"}],"resources":{"limits":{"memory":"512Mi"}},"livenessProbe":{"httpGet":{"path":"/health.php","port":8080,"scheme":"HTTP"},"initialDelaySeconds":30,"timeoutSeconds":3,"periodSeconds":60,"successThreshold":1,"failureThreshold":3},"readinessProbe":{"httpGet":{"path":"/health.php","port":8080,"scheme":"HTTP"},"initialDelaySeconds":3,"timeoutSeconds":3,"periodSeconds":60,"successThreshold":1,"failureThreshold":3},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":2,"observedGeneration":2,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"image change","causes":[{"type":"ImageChange","imageTrigger":{"from":{"kind":"DockerImage","name":"docker-registry.default.svc:5000/cloud-test/cakephp-mysql-persistent@sha256:4b81316236687c001a2c1afa2b2b4b7db412dca8264c378217700946509d0fef"}}}]},"conditions":[{"type":"Available","status":"False","lastUpdateTime":"2018-11-19T10:39:50Z","lastTransitionTime":"2018-11-19T10:39:50Z","message":"Deployment config does not have minimum availability."},{"type":"Progressing","status":"Unknown","lastUpdateTime":"2018-11-19T10:41:44Z","lastTransitionTime":"2018-11-19T10:41:44Z","message":"replication controller \"cakephp-mysql-persistent-1\" is waiting for pod \"cakephp-mysql-persistent-1-deploy\" to run"}]}}
  creationTimestamp: null
  generation: 1
  labels:
    app: cakephp-mysql-persistent
    openshift.io/deployment-config.name: cakephp-mysql-persistent
    template: cakephp-mysql-persistent
  name: cakephp-mysql-persistent-2
  ownerReferences:
  - apiVersion: apps.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: DeploymentConfig
    name: cakephp-mysql-persistent
    uid: 718d8164-ebe7-11e8-ba2b-0aa0c5b29fe8
spec:
  replicas: 1
  selector:
    deployment: cakephp-mysql-persistent-2
    deploymentconfig: cakephp-mysql-persistent
    name: cakephp-mysql-persistent
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: "2"
        openshift.io/deployment-config.name: cakephp-mysql-persistent
        openshift.io/deployment.name: cakephp-mysql-persistent-2
      creationTimestamp: null
      labels:
        deployment: cakephp-mysql-persistent-2
        deploymentconfig: cakephp-mysql-persistent
        name: cakephp-mysql-persistent
    spec:
      containers:
      - env:
        - name: DATABASE_SERVICE_NAME
          value: mysql
        - name: DATABASE_ENGINE
          value: mysql
        - name: DATABASE_NAME
          value: default
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: cakephp-mysql-persistent
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: cakephp-mysql-persistent
        - name: CAKEPHP_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              key: cakephp-secret-token
              name: cakephp-mysql-persistent
        - name: CAKEPHP_SECURITY_SALT
          valueFrom:
            secretKeyRef:
              key: cakephp-security-salt
              name: cakephp-mysql-persistent
        - name: CAKEPHP_SECURITY_CIPHER_SEED
          valueFrom:
            secretKeyRef:
              key: cakephp-security-cipher-seed
              name: cakephp-mysql-persistent
        - name: OPCACHE_REVALIDATE_FREQ
          value: "2"
        image: docker-registry.default.svc:5000/cloud-test/cakephp-mysql-persistent@sha256:4b81316236687c001a2c1afa2b2b4b7db412dca8264c378217700946509d0fef
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health.php
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 3
        name: cakephp-mysql-persistent
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health.php
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  replicas: 0
