apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    openshift.io/deployer-pod.completed-at: 2018-11-19 10:49:05 +0000 UTC
    openshift.io/deployer-pod.created-at: 2018-11-19 10:50:06 +0000 UTC
    openshift.io/deployer-pod.name: django-ex-1-deploy
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: django-ex
    openshift.io/deployment.phase: Complete
    openshift.io/deployment.replicas: "1"
    openshift.io/deployment.status-reason: config change
    openshift.io/encoded-deployment-config: |
      {"kind":"DeploymentConfig","apiVersion":"v1","metadata":{"name":"django-ex","namespace":"cloud-test","selfLink":"/apis/apps.openshift.io/v1/namespaces/cloud-test/deploymentconfigs/django-ex","uid":"cdc2fad3-ebe8-11e8-ba2b-0aa0c5b29fe8","resourceVersion":"2963143","generation":3,"creationTimestamp":"2018-11-19T10:49:35Z","labels":{"app":"django-ex"},"annotations":{"openshift.io/generated-by":"OpenShiftWebConsole"}},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["django-ex"],"from":{"kind":"ImageStreamTag","namespace":"cloud-test","name":"django-ex:latest"},"lastTriggeredImage":"docker-registry.default.svc:5000/cloud-test/django-ex@sha256:f775fbb42b7b0b5cdf3fd13d6a0e4d792efbddd996444501506686c20027e952"}},{"type":"ConfigChange"}],"replicas":1,"test":false,"selector":{"deploymentconfig":"django-ex"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"django-ex","deploymentconfig":"django-ex"}},"spec":{"containers":[{"name":"django-ex","image":"docker-registry.default.svc:5000/cloud-test/django-ex@sha256:f775fbb42b7b0b5cdf3fd13d6a0e4d792efbddd996444501506686c20027e952","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":1,"observedGeneration":1,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"config change","causes":[{"type":"ConfigChange"}]},"conditions":[{"type":"Available","status":"False","lastUpdateTime":"2018-11-19T10:49:35Z","lastTransitionTime":"2018-11-19T10:49:35Z","message":"Deployment config does not have minimum availability."}]}}
  creationTimestamp: null
  generation: 1
  labels:
    app: django-ex
    openshift.io/deployment-config.name: django-ex
  name: django-ex-1
  ownerReferences:
  - apiVersion: apps.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: DeploymentConfig
    name: django-ex
    uid: cdc2fad3-ebe8-11e8-ba2b-0aa0c5b29fe8
spec:
  replicas: 1
  selector:
    deployment: django-ex-1
    deploymentconfig: django-ex
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: "1"
        openshift.io/deployment-config.name: django-ex
        openshift.io/deployment.name: django-ex-1
      creationTimestamp: null
      labels:
        app: django-ex
        deployment: django-ex-1
        deploymentconfig: django-ex
    spec:
      containers:
      - image: docker-registry.default.svc:5000/cloud-test/django-ex@sha256:f775fbb42b7b0b5cdf3fd13d6a0e4d792efbddd996444501506686c20027e952
        imagePullPolicy: Always
        name: django-ex
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  replicas: 0
