apiVersion: v1
kind: Route
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
    openshift.io/host.generated: "true"
  creationTimestamp: null
  labels:
    app: cakephp-ex
  name: cakephp-ex
spec:
  host: cakephp-ex-sanketcloudform.apps01.amosdemo.io
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: cakephp-ex
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: 2018-11-27T04:09:03Z
      status: "True"
      type: Admitted
    host: cakephp-ex-sanketcloudform.apps01.amosdemo.io
    routerName: router
    wildcardPolicy: None
