apiVersion: v1
groupNames: null
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: system:deployers
roleRef:
  name: system:deployer
subjects:
- kind: ServiceAccount
  name: deployer
  namespace: poc-fuse-springboot-demo-v2
userNames:
- system:serviceaccount:poc-fuse-springboot-demo-v2:deployer
