apiVersion: v1
groupNames:
- system:serviceaccounts:poc-fuse-springboot-demo-v2
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: system:image-pullers
roleRef:
  name: system:image-puller
subjects:
- kind: SystemGroup
  name: system:serviceaccounts:poc-fuse-springboot-demo-v2
userNames: null
