apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: null
  name: core-object-counts
spec:
  hard:
    configmaps: "10"
    persistentvolumeclaims: "4"
    replicationcontrollers: "20"
    secrets: "10"
    services: "10"
status: {}
