apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    app: gogs
  name: gogs-postgresql
subsets:
- notReadyAddresses:
  - ip: 10.131.0.191
    nodeName: amos01-compute001.amosdemo.io
    targetRef:
      kind: Pod
      name: gogs-postgresql-1-vtg65
      namespace: cicd
      resourceVersion: "5662144"
      uid: 4ea51e45-f30c-11e8-ba2b-0aa0c5b29fe8
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
