apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    app: gogs
  name: gogs
subsets:
- notReadyAddresses:
  - ip: 10.131.0.190
    nodeName: amos01-compute001.amosdemo.io
    targetRef:
      kind: Pod
      name: gogs-1-6t4sw
      namespace: cicd
      resourceVersion: "5662325"
      uid: 4e9eee8d-f30c-11e8-ba2b-0aa0c5b29fe8
  ports:
  - name: 3000-tcp
    port: 3000
    protocol: TCP
