apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    app: nexus3
  name: nexus3
subsets:
- addresses:
  - ip: 10.131.0.201
    nodeName: amos01-compute001.amosdemo.io
    targetRef:
      kind: Pod
      name: nexus3-1-ddxjc
      namespace: cicd
      resourceVersion: "5630339"
      uid: 4eac1cf7-f30c-11e8-ba2b-0aa0c5b29fe8
  ports:
  - name: 8081-tcp
    port: 8081
    protocol: TCP
