apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    app: sonarqube
  name: postgresql-sonarqube
subsets:
- notReadyAddresses:
  - ip: 10.131.1.124
    nodeName: amos01-compute001.amosdemo.io
    targetRef:
      kind: Pod
      name: postgresql-sonarqube-1-sm4fn
      namespace: cicd
      resourceVersion: "5662044"
      uid: 5a6354d3-f491-11e8-ba2b-0aa0c5b29fe8
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
