apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    app: tomcat
  name: tomcat
subsets:
- addresses:
  - ip: 10.131.0.194
    nodeName: amos01-compute001.amosdemo.io
    targetRef:
      kind: Pod
      name: tomcat-1-lmqcm
      namespace: cicd
      resourceVersion: "5628876"
      uid: 4eb671b8-f30c-11e8-ba2b-0aa0c5b29fe8
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
