apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kubectl.kubernetes.io/desired-replicas: "1"
    kubectl.kubernetes.io/update-source-id: gogs-1:af059f4a-e707-11e8-b839-0aa0c5b29fe8
    openshift.io/deployer-pod.completed-at: 2018-11-29 06:13:52 +0000 UTC
    openshift.io/deployer-pod.created-at: 2018-11-29 06:05:25 +0000 UTC
    openshift.io/deployer-pod.name: gogs-2-deploy
    openshift.io/deployment-config.latest-version: "2"
    openshift.io/deployment-config.name: gogs
    openshift.io/deployment.phase: Failed
    openshift.io/deployment.replicas: "0"
    openshift.io/deployment.status-reason: manual change
    openshift.io/encoded-deployment-config: |
      {"kind":"DeploymentConfig","apiVersion":"v1","metadata":{"name":"gogs","namespace":"cicd","selfLink":"/apis/apps.openshift.io/v1/namespaces/cicd/deploymentconfigs/gogs","uid":"ae0bd716-e707-11e8-b839-0aa0c5b29fe8","resourceVersion":"4748251","generation":3,"creationTimestamp":"2018-11-13T05:48:00Z","labels":{"app":"gogs"}},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ConfigChange"},{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["gogs"],"from":{"kind":"ImageStreamTag","namespace":"cicd","name":"gogs:0.11.4"},"lastTriggeredImage":"docker.io/openshiftdemos/gogs@sha256:0ef022180ee9d9c55551b8200f41383ade43378e4a8134eb8b8d895dfe171d0a"}}],"replicas":1,"test":false,"selector":{"app":"gogs","deploymentconfig":"gogs"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"gogs","deploymentconfig":"gogs"}},"spec":{"volumes":[{"name":"gogs-data","persistentVolumeClaim":{"claimName":"gogs-data"}},{"name":"gogs-config","configMap":{"name":"gogs-config","items":[{"key":"app.ini","path":"app.ini"}],"defaultMode":420}}],"containers":[{"name":"gogs","image":"docker.io/openshiftdemos/gogs@sha256:0ef022180ee9d9c55551b8200f41383ade43378e4a8134eb8b8d895dfe171d0a","ports":[{"containerPort":3000,"protocol":"TCP"}],"resources":{},"volumeMounts":[{"name":"gogs-data","mountPath":"/opt/gogs/data"},{"name":"gogs-config","mountPath":"/etc/gogs/conf"}],"livenessProbe":{"httpGet":{"path":"/","port":3000,"scheme":"HTTP"},"initialDelaySeconds":20,"timeoutSeconds":1,"periodSeconds":10,"successThreshold":1,"failureThreshold":10},"readinessProbe":{"httpGet":{"path":"/","port":3000,"scheme":"HTTP"},"initialDelaySeconds":3,"timeoutSeconds":1,"periodSeconds":20,"successThreshold":1,"failureThreshold":10},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","serviceAccountName":"gogs","serviceAccount":"gogs","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":2,"observedGeneration":2,"replicas":1,"updatedReplicas":1,"availableReplicas":0,"unavailableReplicas":1,"details":{"message":"manual change","causes":[{"type":"Manual"}]},"conditions":[{"type":"Progressing","status":"True","lastUpdateTime":"2018-11-13T05:49:51Z","lastTransitionTime":"2018-11-13T05:49:51Z","reason":"NewReplicationControllerAvailable","message":"replication controller \"gogs-1\" successfully rolled out"},{"type":"Available","status":"False","lastUpdateTime":"2018-11-28T12:47:01Z","lastTransitionTime":"2018-11-28T12:47:01Z","message":"Deployment config does not have minimum availability."}]}}
  creationTimestamp: null
  generation: 1
  labels:
    app: gogs
    openshift.io/deployment-config.name: gogs
  name: gogs-2
  ownerReferences:
  - apiVersion: apps.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: DeploymentConfig
    name: gogs
    uid: ae0bd716-e707-11e8-b839-0aa0c5b29fe8
spec:
  replicas: 0
  selector:
    app: gogs
    deployment: gogs-2
    deploymentconfig: gogs
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: "2"
        openshift.io/deployment-config.name: gogs
        openshift.io/deployment.name: gogs-2
      creationTimestamp: null
      labels:
        app: gogs
        deployment: gogs-2
        deploymentconfig: gogs
    spec:
      containers:
      - image: docker.io/openshiftdemos/gogs@sha256:0ef022180ee9d9c55551b8200f41383ade43378e4a8134eb8b8d895dfe171d0a
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: gogs
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/gogs/data
          name: gogs-data
        - mountPath: /etc/gogs/conf
          name: gogs-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: gogs
      serviceAccountName: gogs
      terminationGracePeriodSeconds: 30
      volumes:
      - name: gogs-data
        persistentVolumeClaim:
          claimName: gogs-data
      - configMap:
          defaultMode: 420
          items:
          - key: app.ini
            path: app.ini
          name: gogs-config
        name: gogs-config
status:
  replicas: 0
