apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kubectl.kubernetes.io/desired-replicas: "1"
    openshift.io/deployer-pod.completed-at: 2018-11-29 03:57:08 +0000 UTC
    openshift.io/deployer-pod.created-at: 2018-11-29 03:47:55 +0000 UTC
    openshift.io/deployer-pod.name: postgresql-sonarqube-2-deploy
    openshift.io/deployment-config.latest-version: "2"
    openshift.io/deployment-config.name: postgresql-sonarqube
    openshift.io/deployment.phase: Failed
    openshift.io/deployment.replicas: "0"
    openshift.io/deployment.status-reason: manual change
    openshift.io/encoded-deployment-config: |
      {"kind":"DeploymentConfig","apiVersion":"v1","metadata":{"name":"postgresql-sonarqube","namespace":"cicd","selfLink":"/apis/apps.openshift.io/v1/namespaces/cicd/deploymentconfigs/postgresql-sonarqube","uid":"13ceb3d9-e708-11e8-b839-0aa0c5b29fe8","resourceVersion":"4730958","generation":3,"creationTimestamp":"2018-11-13T05:50:51Z","labels":{"app":"sonarqube","deploymentconfig":"postgresql-sonarqube"},"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"}},"spec":{"strategy":{"type":"Recreate","recreateParams":{"timeoutSeconds":600},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["postgresql"],"from":{"kind":"ImageStreamTag","namespace":"openshift","name":"postgresql:9.5"},"lastTriggeredImage":"registry.access.redhat.com/rhscl/postgresql-95-rhel7@sha256:eb7c6fa06fce6d4efc55b7311dd45797a26bd4d8ec4648056ec068b7a4653ec8"}},{"type":"ConfigChange"}],"replicas":1,"revisionHistoryLimit":10,"test":false,"selector":{"app":"sonarqube","deploymentconfig":"postgresql-sonarqube"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"sonarqube","deploymentconfig":"postgresql-sonarqube"},"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"}},"spec":{"volumes":[{"name":"postgresql-data","persistentVolumeClaim":{"claimName":"postgresql-sonarqube-data"}}],"containers":[{"name":"postgresql","image":"registry.access.redhat.com/rhscl/postgresql-95-rhel7@sha256:eb7c6fa06fce6d4efc55b7311dd45797a26bd4d8ec4648056ec068b7a4653ec8","ports":[{"containerPort":5432,"protocol":"TCP"}],"env":[{"name":"POSTGRESQL_USER","value":"sonar"},{"name":"POSTGRESQL_PASSWORD","value":"Fv8qVNcLM8yt1iUO"},{"name":"POSTGRESQL_DATABASE","value":"sonar"}],"resources":{"limits":{"memory":"256Mi"}},"volumeMounts":[{"name":"postgresql-data","mountPath":"/var/lib/pgsql/data"}],"livenessProbe":{"tcpSocket":{"port":5432},"initialDelaySeconds":30,"timeoutSeconds":1,"periodSeconds":10,"successThreshold":1,"failureThreshold":3},"readinessProbe":{"exec":{"command":["/bin/sh","-i","-c","psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c 'SELECT 1'"]},"initialDelaySeconds":5,"timeoutSeconds":1,"periodSeconds":10,"successThreshold":1,"failureThreshold":3},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent","securityContext":{"capabilities":{},"privileged":false}}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":2,"observedGeneration":2,"replicas":1,"updatedReplicas":1,"availableReplicas":0,"unavailableReplicas":1,"details":{"message":"manual change","causes":[{"type":"Manual"}]},"conditions":[{"type":"Progressing","status":"True","lastUpdateTime":"2018-11-13T05:51:54Z","lastTransitionTime":"2018-11-13T05:51:54Z","reason":"NewReplicationControllerAvailable","message":"replication controller \"postgresql-sonarqube-1\" successfully rolled out"},{"type":"Available","status":"False","lastUpdateTime":"2018-11-28T12:47:01Z","lastTransitionTime":"2018-11-28T12:47:01Z","message":"Deployment config does not have minimum availability."}]}}
  creationTimestamp: null
  generation: 1
  labels:
    app: sonarqube
    deploymentconfig: postgresql-sonarqube
    openshift.io/deployment-config.name: postgresql-sonarqube
  name: postgresql-sonarqube-2
  ownerReferences:
  - apiVersion: apps.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: DeploymentConfig
    name: postgresql-sonarqube
    uid: 13ceb3d9-e708-11e8-b839-0aa0c5b29fe8
spec:
  replicas: 0
  selector:
    app: sonarqube
    deployment: postgresql-sonarqube-2
    deploymentconfig: postgresql-sonarqube
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: "2"
        openshift.io/deployment-config.name: postgresql-sonarqube
        openshift.io/deployment.name: postgresql-sonarqube-2
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: sonarqube
        deployment: postgresql-sonarqube-2
        deploymentconfig: postgresql-sonarqube
    spec:
      containers:
      - env:
        - name: POSTGRESQL_USER
          value: sonar
        - name: POSTGRESQL_PASSWORD
          value: Fv8qVNcLM8yt1iUO
        - name: POSTGRESQL_DATABASE
          value: sonar
        image: registry.access.redhat.com/rhscl/postgresql-95-rhel7@sha256:eb7c6fa06fce6d4efc55b7311dd45797a26bd4d8ec4648056ec068b7a4653ec8
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5432
          timeoutSeconds: 1
        name: postgresql
        ports:
        - containerPort: 5432
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c
              'SELECT 1'
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 256Mi
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: postgresql-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: postgresql-sonarqube-data
status:
  replicas: 0
