apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  generation: 19
  name: jboss
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/test1/jboss:test
    generation: 19
    importPolicy: {}
    name: test
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
