apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    openshift.io/image.dockerRepositoryCheck: 2018-12-04T04:50:47Z
  creationTimestamp: null
  generation: 2
  labels:
    app: nexus3
  name: nexus3
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: sonatype/nexus3
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/cicd-demo/nexus3:latest
    generation: 2
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
