apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
    openshift.io/image.dockerRepositoryCheck: 2018-12-04T04:55:56Z
  creationTimestamp: null
  generation: 2
  labels:
    build: mavenapp
  name: websphere-liberty
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: websphere-liberty:latest
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/cicd-demo/websphere-liberty:latest
    generation: 2
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
