apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    openshift.io/deployer-pod.completed-at: 2018-11-13 10:24:13 +0000 UTC
    openshift.io/deployer-pod.created-at: 2018-11-13 10:24:54 +0000 UTC
    openshift.io/deployer-pod.name: php-2-deploy
    openshift.io/deployment-config.latest-version: "2"
    openshift.io/deployment-config.name: php
    openshift.io/deployment.phase: Complete
    openshift.io/deployment.replicas: "1"
    openshift.io/deployment.status-reason: image change
    openshift.io/encoded-deployment-config: |
      {"kind":"DeploymentConfig","apiVersion":"v1","metadata":{"name":"php","namespace":"devpipeline","selfLink":"/apis/apps.openshift.io/v1/namespaces/devpipeline/deploymentconfigs/php","uid":"5905f2a0-e72e-11e8-b839-0aa0c5b29fe8","resourceVersion":"1699386","generation":3,"creationTimestamp":"2018-11-13T10:24:48Z","labels":{"app":"php"},"annotations":{"openshift.io/generated-by":"OpenShiftWebConsole"}},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["php"],"from":{"kind":"ImageStreamTag","namespace":"devpipeline","name":"php:latest"},"lastTriggeredImage":"docker-registry.default.svc:5000/devpipeline/php@sha256:e5fe5da8b74077117df579e1c4a4b512aee3ab08cff4a130b4cfce88add9f4fc"}},{"type":"ConfigChange"}],"replicas":1,"test":false,"selector":{"deploymentconfig":"php"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"php","deploymentconfig":"php"}},"spec":{"containers":[{"name":"php","image":"docker-registry.default.svc:5000/devpipeline/php@sha256:e5fe5da8b74077117df579e1c4a4b512aee3ab08cff4a130b4cfce88add9f4fc","ports":[{"containerPort":8080,"protocol":"TCP"},{"containerPort":8443,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":2,"observedGeneration":1,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"image change","causes":[{"type":"ImageChange","imageTrigger":{"from":{"kind":"DockerImage","name":"docker-registry.default.svc:5000/devpipeline/php@sha256:e5fe5da8b74077117df579e1c4a4b512aee3ab08cff4a130b4cfce88add9f4fc"}}}]},"conditions":[{"type":"Available","status":"False","lastUpdateTime":"2018-11-13T10:24:48Z","lastTransitionTime":"2018-11-13T10:24:48Z","message":"Deployment config does not have minimum availability."}]}}
  creationTimestamp: null
  generation: 1
  labels:
    app: php
    openshift.io/deployment-config.name: php
  name: php-2
  ownerReferences:
  - apiVersion: apps.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: DeploymentConfig
    name: php
    uid: 5905f2a0-e72e-11e8-b839-0aa0c5b29fe8
spec:
  replicas: 1
  selector:
    deployment: php-2
    deploymentconfig: php
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: "2"
        openshift.io/deployment-config.name: php
        openshift.io/deployment.name: php-2
      creationTimestamp: null
      labels:
        app: php
        deployment: php-2
        deploymentconfig: php
    spec:
      containers:
      - image: docker-registry.default.svc:5000/devpipeline/php@sha256:e5fe5da8b74077117df579e1c4a4b512aee3ab08cff4a130b4cfce88add9f4fc
        imagePullPolicy: Always
        name: php
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  replicas: 0
