apiVersion: v1
data:
  cakephp-secret-token: WjdfVFpaUVA2YjliNGZTd21PM2tYVF9OcTVnMDZiS25rR2x2dDBPcllMS1hiOF9LcTE=
  cakephp-security-cipher-seed: NzQ3NjI3MDU3MTg2MDg4MzU0MTIxODUwMTg2MTQz
  cakephp-security-salt: Y2lJOHlUMTNLRE15ZWdTbGlnck1LbjZuRkJIU21xRm5pcGZLYU53dg==
  database-password: bUx0Y0pCNU5lb3RFa21Vdw==
  database-user: Y2FrZXBocA==
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: cakephp-mysql-persistent
    template: cakephp-mysql-persistent
  name: cakephp-mysql-persistent
type: Opaque
