apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/build.name: jboss-3
    openshift.io/scc: privileged
  creationTimestamp: null
  labels:
    openshift.io/build.name: jboss-3
  name: jboss-3-build
  ownerReferences:
  - apiVersion: build.openshift.io/v1
    controller: true
    kind: Build
    name: jboss-3
    uid: f6e62264-f6cd-11e8-ba2b-0aa0c5b29fe8
spec:
  containers:
  - args:
    - --loglevel=0
    command:
    - openshift-sti-build
    env:
    - name: BUILD
      value: |
        {"kind":"Build","apiVersion":"v1","metadata":{"name":"jboss-3","namespace":"devpipeline","selfLink":"/apis/build.openshift.io/v1/namespaces/devpipeline/builds/jboss-3","uid":"f6e62264-f6cd-11e8-ba2b-0aa0c5b29fe8","resourceVersion":"5464078","creationTimestamp":"2018-12-03T07:35:10Z","labels":{"build":"jboss","buildconfig":"jboss","openshift.io/build-config.name":"jboss","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"jboss","openshift.io/build.number":"3"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"jboss","uid":"9e2f590c-f6cc-11e8-ba2b-0aa0c5b29fe8","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Binary","binary":{}},"revision":{"type":"Git","git":{"commit":"862248d7204563f0341dbf5eb86e26d53e512361","author":{"name":"sudhirkr448","email":"ksreddi448@gmail.com"},"committer":{"name":"GitHub","email":"noreply@github.com"},"message":"Delete bc.txt"}},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"registry.access.redhat.com/jboss-eap-7/eap70-openshift@sha256:7b4d8986212601403ca07b320fd5dadb9f624298251620b8f6e2b55f993d9124"}}},"output":{"to":{"kind":"DockerImage","name":"docker-registry.default.svc:5000/devpipeline/jboss:latest"},"pushSecret":{"name":"builder-dockercfg-8hgqx"}},"resources":{},"postCommit":{},"nodeSelector":null,"triggeredBy":null},"status":{"phase":"New","outputDockerImageReference":"docker-registry.default.svc:5000/devpipeline/jboss:latest","config":{"kind":"BuildConfig","namespace":"devpipeline","name":"jboss"},"output":{}}}
    - name: ORIGIN_VERSION
      value: v3.9.27
    - name: ALLOWED_UIDS
      value: 1-
    - name: DROP_CAPS
      value: KILL,MKNOD,SETGID,SETUID
    - name: PUSH_DOCKERCFG_PATH
      value: /var/run/secrets/openshift.io/push
    image: openshift3/ose-sti-builder:v3.9.27
    imagePullPolicy: IfNotPresent
    name: sti-build
    resources: {}
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp/build
      name: buildworkdir
    - mountPath: /var/run/docker.sock
      name: docker-socket
    - mountPath: /var/run/crio/crio.sock
      name: crio-socket
    - mountPath: /var/run/secrets/openshift.io/push
      name: builder-dockercfg-8hgqx-push
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: builder-token-bj4t8
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: builder-dockercfg-8hgqx
  initContainers:
  - args:
    - --loglevel=0
    command:
    - openshift-git-clone
    env:
    - name: BUILD
      value: |
        {"kind":"Build","apiVersion":"v1","metadata":{"name":"jboss-3","namespace":"devpipeline","selfLink":"/apis/build.openshift.io/v1/namespaces/devpipeline/builds/jboss-3","uid":"f6e62264-f6cd-11e8-ba2b-0aa0c5b29fe8","resourceVersion":"5464078","creationTimestamp":"2018-12-03T07:35:10Z","labels":{"build":"jboss","buildconfig":"jboss","openshift.io/build-config.name":"jboss","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"jboss","openshift.io/build.number":"3"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"jboss","uid":"9e2f590c-f6cc-11e8-ba2b-0aa0c5b29fe8","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Binary","binary":{}},"revision":{"type":"Git","git":{"commit":"862248d7204563f0341dbf5eb86e26d53e512361","author":{"name":"sudhirkr448","email":"ksreddi448@gmail.com"},"committer":{"name":"GitHub","email":"noreply@github.com"},"message":"Delete bc.txt"}},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"registry.access.redhat.com/jboss-eap-7/eap70-openshift@sha256:7b4d8986212601403ca07b320fd5dadb9f624298251620b8f6e2b55f993d9124"}}},"output":{"to":{"kind":"DockerImage","name":"docker-registry.default.svc:5000/devpipeline/jboss:latest"},"pushSecret":{"name":"builder-dockercfg-8hgqx"}},"resources":{},"postCommit":{},"nodeSelector":null,"triggeredBy":null},"status":{"phase":"New","outputDockerImageReference":"docker-registry.default.svc:5000/devpipeline/jboss:latest","config":{"kind":"BuildConfig","namespace":"devpipeline","name":"jboss"},"output":{}}}
    - name: ORIGIN_VERSION
      value: v3.9.27
    - name: ALLOWED_UIDS
      value: 1-
    - name: DROP_CAPS
      value: KILL,MKNOD,SETGID,SETUID
    image: openshift3/ose-sti-builder:v3.9.27
    imagePullPolicy: IfNotPresent
    name: git-clone
    resources: {}
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp/build
      name: buildworkdir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: builder-token-bj4t8
      readOnly: true
  - args:
    - --loglevel=0
    command:
    - openshift-manage-dockerfile
    env:
    - name: BUILD
      value: |
        {"kind":"Build","apiVersion":"v1","metadata":{"name":"jboss-3","namespace":"devpipeline","selfLink":"/apis/build.openshift.io/v1/namespaces/devpipeline/builds/jboss-3","uid":"f6e62264-f6cd-11e8-ba2b-0aa0c5b29fe8","resourceVersion":"5464078","creationTimestamp":"2018-12-03T07:35:10Z","labels":{"build":"jboss","buildconfig":"jboss","openshift.io/build-config.name":"jboss","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"jboss","openshift.io/build.number":"3"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"jboss","uid":"9e2f590c-f6cc-11e8-ba2b-0aa0c5b29fe8","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Binary","binary":{}},"revision":{"type":"Git","git":{"commit":"862248d7204563f0341dbf5eb86e26d53e512361","author":{"name":"sudhirkr448","email":"ksreddi448@gmail.com"},"committer":{"name":"GitHub","email":"noreply@github.com"},"message":"Delete bc.txt"}},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"registry.access.redhat.com/jboss-eap-7/eap70-openshift@sha256:7b4d8986212601403ca07b320fd5dadb9f624298251620b8f6e2b55f993d9124"}}},"output":{"to":{"kind":"DockerImage","name":"docker-registry.default.svc:5000/devpipeline/jboss:latest"},"pushSecret":{"name":"builder-dockercfg-8hgqx"}},"resources":{},"postCommit":{},"nodeSelector":null,"triggeredBy":null},"status":{"phase":"New","outputDockerImageReference":"docker-registry.default.svc:5000/devpipeline/jboss:latest","config":{"kind":"BuildConfig","namespace":"devpipeline","name":"jboss"},"output":{}}}
    - name: ORIGIN_VERSION
      value: v3.9.27
    - name: ALLOWED_UIDS
      value: 1-
    - name: DROP_CAPS
      value: KILL,MKNOD,SETGID,SETUID
    image: openshift3/ose-sti-builder:v3.9.27
    imagePullPolicy: IfNotPresent
    name: manage-dockerfile
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp/build
      name: buildworkdir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: builder-token-bj4t8
      readOnly: true
  nodeName: amos01-compute001.amosdemo.io
  nodeSelector:
    node-role.kubernetes.io/compute: "true"
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: builder
  serviceAccountName: builder
  terminationGracePeriodSeconds: 30
  volumes:
  - emptyDir: {}
    name: buildworkdir
  - hostPath:
      path: /var/run/docker.sock
      type: ""
    name: docker-socket
  - hostPath:
      path: /var/run/crio/crio.sock
      type: ""
    name: crio-socket
  - name: builder-dockercfg-8hgqx-push
    secret:
      defaultMode: 384
      secretName: builder-dockercfg-8hgqx
  - name: builder-token-bj4t8
    secret:
      defaultMode: 420
      secretName: builder-token-bj4t8
status:
  phase: Pending
  qosClass: BestEffort
