apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: jboss
    openshift.io/deployment.name: jboss-1
    openshift.io/generated-by: OpenShiftNewApp
    openshift.io/scc: anyuid
  creationTimestamp: null
  generateName: jboss-1-
  labels:
    app: jboss
    deployment: jboss-1
    deploymentconfig: jboss
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: jboss-1
    uid: c50fe9af-f793-11e8-ba2b-0aa0c5b29fe8
spec:
  containers:
  - image: docker-registry.default.svc:5000/devpipeline/jboss@sha256:9c22edb15d9d5d06dac658c4e4fa7a4c8a0a54d120b53b8c63a279e034612793
    imagePullPolicy: IfNotPresent
    name: jboss
    ports:
    - containerPort: 8778
      protocol: TCP
    - containerPort: 8080
      protocol: TCP
    - containerPort: 8443
      protocol: TCP
    resources: {}
    securityContext:
      capabilities:
        drop:
        - MKNOD
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-jrtdk
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: default-dockercfg-ts7vt
  nodeName: amos01-compute001.amosdemo.io
  nodeSelector:
    node-role.kubernetes.io/compute: "true"
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    seLinuxOptions:
      level: s0:c9,c4
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: default-token-jrtdk
    secret:
      defaultMode: 420
      secretName: default-token-jrtdk
status:
  phase: Pending
  qosClass: BestEffort
