apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/deployment-config.latest-version: "2"
    openshift.io/deployment-config.name: phprest
    openshift.io/deployment.name: phprest-2
    openshift.io/scc: anyuid
  creationTimestamp: null
  generateName: phprest-2-
  labels:
    app: phprest
    deployment: phprest-2
    deploymentconfig: phprest
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: phprest-2
    uid: d0acb539-ee16-11e8-ba2b-0aa0c5b29fe8
spec:
  containers:
  - image: docker-registry.default.svc:5000/devpipeline/phprest@sha256:1a17b5369dd1b4d4328824277e76211104aeef2865036a5cc29909ed9eae28b5
    imagePullPolicy: Always
    name: phprest
    ports:
    - containerPort: 8080
      protocol: TCP
    - containerPort: 8443
      protocol: TCP
    resources: {}
    securityContext:
      capabilities:
        drop:
        - MKNOD
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-jrtdk
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: default-dockercfg-ts7vt
  nodeName: amos01-compute001.amosdemo.io
  nodeSelector:
    node-role.kubernetes.io/compute: "true"
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    seLinuxOptions:
      level: s0:c9,c4
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: default-token-jrtdk
    secret:
      defaultMode: 420
      secretName: default-token-jrtdk
status:
  phase: Pending
  qosClass: BestEffort
