apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    app: openshift-web-console
  name: webconsole
subsets:
- addresses:
  - ip: 10.128.0.90
    nodeName: amos01-master001.amosdemo.io
    targetRef:
      kind: Pod
      name: webconsole-74c77977fb-hd29j
      namespace: openshift-web-console
      resourceVersion: "5380807"
      uid: 3ffa43d0-dda1-11e8-b362-0aa0c5b29fe8
  ports:
  - name: https
    port: 8443
    protocol: TCP
