apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sonarqube-ephemeral
    template: sonarqube-ephemeral-template
  name: sonar
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    name: sonar
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
