apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    Description: 'Gluster-Internal: Dynamically provisioned PV'
    gluster.kubernetes.io/heketi-volume-id: 767e28ecb13d44d2bf4443d349e82080
    gluster.org/type: file
    kubernetes.io/createdby: heketi-dynamic-provisioner
    pv.beta.kubernetes.io/gid: "2001"
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/glusterfs
    volume.beta.kubernetes.io/mount-options: auto_unmount
  creationTimestamp: null
  name: pvc-f245cfb8-f7a3-11e8-ba2b-0aa0c5b29fe8
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jenkins
    namespace: testsele
    resourceVersion: "5656191"
    uid: f245cfb8-f7a3-11e8-ba2b-0aa0c5b29fe8
  glusterfs:
    endpoints: glusterfs-dynamic-jenkins
    path: vol_767e28ecb13d44d2bf4443d349e82080
  persistentVolumeReclaimPolicy: Delete
  storageClassName: glusterfs-storage
status: {}
