apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    Description: 'Gluster-Internal: Dynamically provisioned PV'
    gluster.kubernetes.io/heketi-volume-id: 4ae3e45b35166edb853f3fb7c56a739b
    gluster.org/type: file
    kubernetes.io/createdby: heketi-dynamic-provisioner
    pv.beta.kubernetes.io/gid: "2003"
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/glusterfs
    volume.beta.kubernetes.io/mount-options: auto_unmount
  creationTimestamp: null
  name: pvc-ae11cc4f-e707-11e8-b839-0aa0c5b29fe8
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: gogs-postgres-data
    namespace: cicd
    resourceVersion: "1663925"
    uid: ae11cc4f-e707-11e8-b839-0aa0c5b29fe8
  glusterfs:
    endpoints: glusterfs-dynamic-gogs-postgres-data
    path: vol_4ae3e45b35166edb853f3fb7c56a739b
  persistentVolumeReclaimPolicy: Delete
  storageClassName: glusterfs-storage
status: {}
