apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    Description: 'Gluster-Internal: Dynamically provisioned PV'
    gluster.kubernetes.io/heketi-volume-id: 1b825072dbd471c9c1c0b7e9d8362f91
    gluster.org/type: file
    kubernetes.io/createdby: heketi-dynamic-provisioner
    pv.beta.kubernetes.io/gid: "2005"
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/glusterfs
    volume.beta.kubernetes.io/mount-options: auto_unmount
  creationTimestamp: null
  name: pvc-f3613aa1-e721-11e8-b839-0aa0c5b29fe8
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: sonarqube-data
    namespace: devpipeline
    resourceVersion: "1686991"
    uid: f3613aa1-e721-11e8-b839-0aa0c5b29fe8
  glusterfs:
    endpoints: glusterfs-dynamic-sonarqube-data
    path: vol_1b825072dbd471c9c1c0b7e9d8362f91
  persistentVolumeReclaimPolicy: Delete
  storageClassName: glusterfs-storage
status: {}
