apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    Description: 'Gluster-Internal: Dynamically provisioned PV'
    gluster.kubernetes.io/heketi-volume-id: eb6587203f838cf860887c84d4cb32ca
    gluster.org/type: file
    kubernetes.io/createdby: heketi-dynamic-provisioner
    pv.beta.kubernetes.io/gid: "2004"
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/glusterfs
    volume.beta.kubernetes.io/mount-options: auto_unmount
  creationTimestamp: null
  name: pvc-13d1ac3f-e708-11e8-b839-0aa0c5b29fe8
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: sonarqube-data
    namespace: cicd
    resourceVersion: "1664517"
    uid: 13d1ac3f-e708-11e8-b839-0aa0c5b29fe8
  glusterfs:
    endpoints: glusterfs-dynamic-sonarqube-data
    path: vol_eb6587203f838cf860887c84d4cb32ca
  persistentVolumeReclaimPolicy: Delete
  storageClassName: glusterfs-storage
status: {}
