apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    Description: 'Gluster-Internal: Dynamically provisioned PV'
    gluster.kubernetes.io/heketi-volume-id: 26bc89c098b0e103053ef024226ce288
    gluster.org/type: file
    kubernetes.io/createdby: heketi-dynamic-provisioner
    pv.beta.kubernetes.io/gid: "2001"
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/glusterfs
    volume.beta.kubernetes.io/mount-options: auto_unmount
  creationTimestamp: null
  name: pvc-32edcf00-f6da-11e8-ba2b-0aa0c5b29fe8
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jenkins
    namespace: vikram
    resourceVersion: "5476023"
    uid: 32edcf00-f6da-11e8-ba2b-0aa0c5b29fe8
  glusterfs:
    endpoints: glusterfs-dynamic-jenkins
    path: vol_26bc89c098b0e103053ef024226ce288
  persistentVolumeReclaimPolicy: Delete
  storageClassName: glusterfs-storage
status: {}
