apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    Description: 'Gluster-Internal: Dynamically provisioned PV'
    gluster.kubernetes.io/heketi-volume-id: cc8aae17741c2574c132930695b3c290
    gluster.org/type: file
    kubernetes.io/createdby: heketi-dynamic-provisioner
    pv.beta.kubernetes.io/gid: "2001"
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/glusterfs
    volume.beta.kubernetes.io/mount-options: auto_unmount
  creationTimestamp: null
  name: pvc-07ae0900-ed67-11e8-ba2b-0aa0c5b29fe8
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: metrics-cassandra-1
    namespace: openshift-infra
    resourceVersion: "3395406"
    uid: 07ae0900-ed67-11e8-ba2b-0aa0c5b29fe8
  glusterfs:
    endpoints: glusterfs-dynamic-metrics-cassandra-1
    path: vol_cc8aae17741c2574c132930695b3c290
  persistentVolumeReclaimPolicy: Delete
  storageClassName: glusterfs-storage
status: {}
