apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    gluster.kubernetes.io/provisioned-for-pvc: postgresql-sonarqube-data
  name: glusterfs-dynamic-postgresql-sonarqube-data
spec:
  ports:
  - port: 1
    protocol: TCP
    targetPort: 1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
