apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    app: nexus3
  name: nexus3
subsets:
- addresses:
  - ip: 10.131.0.206
    nodeName: amos01-compute001.amosdemo.io
    targetRef:
      kind: Pod
      name: nexus3-1-fbmmf
      namespace: devpipeline
      resourceVersion: "5637747"
      uid: 4ed4acb7-f30c-11e8-ba2b-0aa0c5b29fe8
  ports:
  - name: 8081-tcp
    port: 8081
    protocol: TCP
