apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    app: php
  name: php
subsets:
- addresses:
  - ip: 10.131.0.209
    nodeName: amos01-compute001.amosdemo.io
    targetRef:
      kind: Pod
      name: php-2-sx5bf
      namespace: devpipeline
      resourceVersion: "5628986"
      uid: 4ee4ff67-f30c-11e8-ba2b-0aa0c5b29fe8
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
