apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    app: phprest
  name: phprest
subsets:
- addresses:
  - ip: 10.131.0.196
    nodeName: amos01-compute001.amosdemo.io
    targetRef:
      kind: Pod
      name: phprest-2-w2mxt
      namespace: devpipeline
      resourceVersion: "5628996"
      uid: 4ef2ffcb-f30c-11e8-ba2b-0aa0c5b29fe8
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
