apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    app: sonarqube
  name: postgresql-sonarqube
subsets:
- notReadyAddresses:
  - ip: 10.131.0.200
    nodeName: amos01-compute001.amosdemo.io
    targetRef:
      kind: Pod
      name: postgresql-sonarqube-1-24dpn
      namespace: devpipeline
      resourceVersion: "5662078"
      uid: 4ef3dd2a-f30c-11e8-ba2b-0aa0c5b29fe8
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
