apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    app: sonarqube
  name: sonarqube
subsets:
- notReadyAddresses:
  - ip: 10.131.0.208
    nodeName: amos01-compute001.amosdemo.io
    targetRef:
      kind: Pod
      name: sonarqube-1-6w9rv
      namespace: devpipeline
      resourceVersion: "5661927"
      uid: 4ef7ca21-f30c-11e8-ba2b-0aa0c5b29fe8
  ports:
  - name: sonarqube
    port: 9000
    protocol: TCP
