apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: glusterblock-storage-provisioner-dc
    openshift.io/deployment.name: glusterblock-storage-provisioner-dc-1
    openshift.io/scc: restricted
  creationTimestamp: null
  generateName: glusterblock-storage-provisioner-dc-1-
  labels:
    deployment: glusterblock-storage-provisioner-dc-1
    deploymentconfig: glusterblock-storage-provisioner-dc
    glusterfs: block-storage-provisioner-pod
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: glusterblock-storage-provisioner-dc-1
    uid: b6a90225-dd9f-11e8-b362-0aa0c5b29fe8
spec:
  containers:
  - env:
    - name: PROVISIONER_NAME
      value: gluster.org/glusterblock
    image: rhgs3/rhgs-gluster-block-prov-rhel7:latest
    imagePullPolicy: IfNotPresent
    name: glusterblock-provisioner
    resources: {}
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000070000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: glusterblock-storage-provisioner-token-kf8kx
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: glusterblock-storage-provisioner-dockercfg-nv6db
  nodeName: amos01-master001.amosdemo.io
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000070000
    seLinuxOptions:
      level: s0:c8,c7
  serviceAccount: glusterblock-storage-provisioner
  serviceAccountName: glusterblock-storage-provisioner
  terminationGracePeriodSeconds: 30
  volumes:
  - name: glusterblock-storage-provisioner-token-kf8kx
    secret:
      defaultMode: 420
      secretName: glusterblock-storage-provisioner-token-kf8kx
status:
  phase: Pending
  qosClass: BestEffort
