apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/deployment-config.latest-version: "2"
    openshift.io/deployment-config.name: heketi-storage
    openshift.io/deployment.name: heketi-storage-2
    openshift.io/scc: privileged
  creationTimestamp: null
  generateName: heketi-storage-2-
  labels:
    deployment: heketi-storage-2
    deploymentconfig: heketi-storage
    glusterfs: heketi-storage-pod
    heketi: storage-pod
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: heketi-storage-2
    uid: d76fc1d5-ecb5-11e8-ba2b-0aa0c5b29fe8
spec:
  containers:
  - env:
    - name: HEKETI_USER_KEY
      value: CabUJlQR2QKshq+kxTcGVUwGq9Puc9HbfdL6y41bRb0=
    - name: HEKETI_ADMIN_KEY
      value: TmkSkl56jWhvo0dAsIlfFo1XS24wJKgqWwDieG2NdxE=
    - name: HEKETI_EXECUTOR
      value: kubernetes
    - name: HEKETI_FSTAB
      value: /var/lib/heketi/fstab
    - name: HEKETI_SNAPSHOT_LIMIT
      value: "14"
    - name: HEKETI_KUBE_GLUSTER_DAEMONSET
      value: "1"
    - name: HEKETI_IGNORE_STALE_OPERATIONS
      value: "true"
    image: rhgs3/rhgs-volmanager-rhel7:latest
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /hello
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 3
    name: heketi
    ports:
    - containerPort: 8080
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /hello
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 3
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/heketi
      name: db
    - mountPath: /etc/heketi
      name: config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: heketi-storage-service-account-token-4mlg9
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: heketi-storage-service-account-dockercfg-qpp54
  nodeName: amos01-master001.amosdemo.io
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: heketi-storage-service-account
  serviceAccountName: heketi-storage-service-account
  terminationGracePeriodSeconds: 30
  volumes:
  - glusterfs:
      endpoints: heketi-db-storage-endpoints
      path: heketidbstorage
    name: db
  - name: config
    secret:
      defaultMode: 420
      secretName: heketi-storage-config-secret
  - name: heketi-storage-service-account-token-4mlg9
    secret:
      defaultMode: 420
      secretName: heketi-storage-service-account-token-4mlg9
status:
  phase: Pending
  qosClass: BestEffort
