apiVersion: v1
data:
  hawkular-metrics.htpasswd: aGF3a3VsYXI6JGFwcjEkZmZuWUQydDEkN0J0cVV0bjJnRklpOG42dFp6ZDVVLgo=
  hawkular-metrics.password: bjFpOHpRVWMyUjVldVVC
  hawkular-metrics.username: aGF3a3VsYXI=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"hawkular-metrics.htpasswd":"aGF3a3VsYXI6JGFwcjEkZmZuWUQydDEkN0J0cVV0bjJnRklpOG42dFp6ZDVVLgo=","hawkular-metrics.password":"bjFpOHpRVWMyUjVldVVC","hawkular-metrics.username":"aGF3a3VsYXI="},"kind":"Secret","metadata":{"annotations":{},"labels":{"metrics-infra":"hawkular-metrics"},"name":"hawkular-metrics-account","namespace":"openshift-infra"}}
  creationTimestamp: null
  labels:
    metrics-infra: hawkular-metrics
  name: hawkular-metrics-account
type: Opaque
