apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: jenkins
    openshift.io/deployment.name: jenkins-1
    openshift.io/scc: anyuid
  creationTimestamp: null
  generateName: jenkins-1-
  labels:
    deployment: jenkins-1
    deploymentconfig: jenkins
    name: jenkins
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: jenkins-1
    uid: f2e541b7-f7a3-11e8-ba2b-0aa0c5b29fe8
spec:
  containers:
  - env:
    - name: OPENSHIFT_ENABLE_OAUTH
      value: "true"
    - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
      value: "true"
    - name: KUBERNETES_MASTER
      value: https://kubernetes.default:443
    - name: KUBERNETES_TRUST_CERTIFICATES
      value: "true"
    - name: JENKINS_SERVICE_NAME
      value: jenkins
    - name: JNLP_SERVICE_NAME
      value: jenkins-jnlp
    image: registry.access.redhat.com/openshift3/jenkins-2-rhel7@sha256:45453170e8aedb2648e8ac67d65c435f2c32d7d4c09a1ea4e193e18233d7f3d2
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 2
      httpGet:
        path: /login
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 420
      periodSeconds: 360
      successThreshold: 1
      timeoutSeconds: 240
    name: jenkins
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /login
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 240
    resources:
      limits:
        memory: 1Gi
      requests:
        memory: 1Gi
    securityContext:
      capabilities:
        drop:
        - MKNOD
      privileged: false
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/jenkins
      name: jenkins-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: jenkins-token-xdkdq
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: jenkins-dockercfg-22ld9
  nodeName: amos01-compute001.amosdemo.io
  nodeSelector:
    node-role.kubernetes.io/compute: "true"
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    seLinuxOptions:
      level: s0:c23,c7
  serviceAccount: jenkins
  serviceAccountName: jenkins
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: jenkins-data
    persistentVolumeClaim:
      claimName: jenkins
  - name: jenkins-token-xdkdq
    secret:
      defaultMode: 420
      secretName: jenkins-token-xdkdq
status:
  phase: Pending
  qosClass: Burstable
