apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    app: ruby-ex
  name: ruby-ex
subsets:
- addresses:
  - ip: 10.131.1.128
    nodeName: amos01-compute001.amosdemo.io
    targetRef:
      kind: Pod
      name: ruby-ex-2-mhqtk
      namespace: abcd
      resourceVersion: "5628862"
      uid: d010e388-f494-11e8-ba2b-0aa0c5b29fe8
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
