apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/build.name: jboss-25
    openshift.io/scc: privileged
  creationTimestamp: null
  labels:
    openshift.io/build.name: jboss-25
  name: jboss-25-build
  ownerReferences:
  - apiVersion: build.openshift.io/v1
    controller: true
    kind: Build
    name: jboss-25
    uid: d8e869bb-f6fd-11e8-ba2b-0aa0c5b29fe8
spec:
  containers:
  - args:
    - --loglevel=0
    command:
    - openshift-sti-build
    env:
    - name: BUILD
      value: |
        {"kind":"Build","apiVersion":"v1","metadata":{"name":"jboss-25","namespace":"cicd","selfLink":"/apis/build.openshift.io/v1/namespaces/cicd/builds/jboss-25","uid":"d8e869bb-f6fd-11e8-ba2b-0aa0c5b29fe8","resourceVersion":"5509976","creationTimestamp":"2018-12-03T13:17:56Z","labels":{"build":"jboss","buildconfig":"jboss","openshift.io/build-config.name":"jboss","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"jboss","openshift.io/build.number":"25"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"jboss","uid":"ed248994-e97d-11e8-ba2b-0aa0c5b29fe8","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Binary","binary":{}},"revision":{"type":"Git","git":{"commit":"972f95a15b625a8b55020e0e35c70fd81b9de828","author":{"name":"sudhirkr448","email":"ksreddi448@gmail.com"},"committer":{"name":"GitHub","email":"noreply@github.com"},"message":"Update index.jsp"}},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"registry.access.redhat.com/jboss-eap-7/eap70-openshift@sha256:7b4d8986212601403ca07b320fd5dadb9f624298251620b8f6e2b55f993d9124"}}},"output":{"to":{"kind":"DockerImage","name":"docker-registry.default.svc:5000/cicd/jboss:latest"},"pushSecret":{"name":"builder-dockercfg-dhxm4"}},"resources":{},"postCommit":{},"nodeSelector":null,"triggeredBy":null},"status":{"phase":"New","outputDockerImageReference":"docker-registry.default.svc:5000/cicd/jboss:latest","config":{"kind":"BuildConfig","namespace":"cicd","name":"jboss"},"output":{}}}
    - name: ORIGIN_VERSION
      value: v3.9.27
    - name: ALLOWED_UIDS
      value: 1-
    - name: DROP_CAPS
      value: KILL,MKNOD,SETGID,SETUID
    - name: PUSH_DOCKERCFG_PATH
      value: /var/run/secrets/openshift.io/push
    image: openshift3/ose-sti-builder:v3.9.27
    imagePullPolicy: IfNotPresent
    name: sti-build
    resources: {}
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp/build
      name: buildworkdir
    - mountPath: /var/run/docker.sock
      name: docker-socket
    - mountPath: /var/run/crio/crio.sock
      name: crio-socket
    - mountPath: /var/run/secrets/openshift.io/push
      name: builder-dockercfg-dhxm4-push
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: builder-token-rfvmh
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: builder-dockercfg-dhxm4
  initContainers:
  - args:
    - --loglevel=0
    command:
    - openshift-git-clone
    env:
    - name: BUILD
      value: |
        {"kind":"Build","apiVersion":"v1","metadata":{"name":"jboss-25","namespace":"cicd","selfLink":"/apis/build.openshift.io/v1/namespaces/cicd/builds/jboss-25","uid":"d8e869bb-f6fd-11e8-ba2b-0aa0c5b29fe8","resourceVersion":"5509976","creationTimestamp":"2018-12-03T13:17:56Z","labels":{"build":"jboss","buildconfig":"jboss","openshift.io/build-config.name":"jboss","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"jboss","openshift.io/build.number":"25"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"jboss","uid":"ed248994-e97d-11e8-ba2b-0aa0c5b29fe8","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Binary","binary":{}},"revision":{"type":"Git","git":{"commit":"972f95a15b625a8b55020e0e35c70fd81b9de828","author":{"name":"sudhirkr448","email":"ksreddi448@gmail.com"},"committer":{"name":"GitHub","email":"noreply@github.com"},"message":"Update index.jsp"}},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"registry.access.redhat.com/jboss-eap-7/eap70-openshift@sha256:7b4d8986212601403ca07b320fd5dadb9f624298251620b8f6e2b55f993d9124"}}},"output":{"to":{"kind":"DockerImage","name":"docker-registry.default.svc:5000/cicd/jboss:latest"},"pushSecret":{"name":"builder-dockercfg-dhxm4"}},"resources":{},"postCommit":{},"nodeSelector":null,"triggeredBy":null},"status":{"phase":"New","outputDockerImageReference":"docker-registry.default.svc:5000/cicd/jboss:latest","config":{"kind":"BuildConfig","namespace":"cicd","name":"jboss"},"output":{}}}
    - name: ORIGIN_VERSION
      value: v3.9.27
    - name: ALLOWED_UIDS
      value: 1-
    - name: DROP_CAPS
      value: KILL,MKNOD,SETGID,SETUID
    image: openshift3/ose-sti-builder:v3.9.27
    imagePullPolicy: IfNotPresent
    name: git-clone
    resources: {}
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp/build
      name: buildworkdir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: builder-token-rfvmh
      readOnly: true
  - args:
    - --loglevel=0
    command:
    - openshift-manage-dockerfile
    env:
    - name: BUILD
      value: |
        {"kind":"Build","apiVersion":"v1","metadata":{"name":"jboss-25","namespace":"cicd","selfLink":"/apis/build.openshift.io/v1/namespaces/cicd/builds/jboss-25","uid":"d8e869bb-f6fd-11e8-ba2b-0aa0c5b29fe8","resourceVersion":"5509976","creationTimestamp":"2018-12-03T13:17:56Z","labels":{"build":"jboss","buildconfig":"jboss","openshift.io/build-config.name":"jboss","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"jboss","openshift.io/build.number":"25"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"jboss","uid":"ed248994-e97d-11e8-ba2b-0aa0c5b29fe8","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Binary","binary":{}},"revision":{"type":"Git","git":{"commit":"972f95a15b625a8b55020e0e35c70fd81b9de828","author":{"name":"sudhirkr448","email":"ksreddi448@gmail.com"},"committer":{"name":"GitHub","email":"noreply@github.com"},"message":"Update index.jsp"}},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"registry.access.redhat.com/jboss-eap-7/eap70-openshift@sha256:7b4d8986212601403ca07b320fd5dadb9f624298251620b8f6e2b55f993d9124"}}},"output":{"to":{"kind":"DockerImage","name":"docker-registry.default.svc:5000/cicd/jboss:latest"},"pushSecret":{"name":"builder-dockercfg-dhxm4"}},"resources":{},"postCommit":{},"nodeSelector":null,"triggeredBy":null},"status":{"phase":"New","outputDockerImageReference":"docker-registry.default.svc:5000/cicd/jboss:latest","config":{"kind":"BuildConfig","namespace":"cicd","name":"jboss"},"output":{}}}
    - name: ORIGIN_VERSION
      value: v3.9.27
    - name: ALLOWED_UIDS
      value: 1-
    - name: DROP_CAPS
      value: KILL,MKNOD,SETGID,SETUID
    image: openshift3/ose-sti-builder:v3.9.27
    imagePullPolicy: IfNotPresent
    name: manage-dockerfile
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp/build
      name: buildworkdir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: builder-token-rfvmh
      readOnly: true
  nodeName: amos01-compute001.amosdemo.io
  nodeSelector:
    node-role.kubernetes.io/compute: "true"
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: builder
  serviceAccountName: builder
  terminationGracePeriodSeconds: 30
  volumes:
  - emptyDir: {}
    name: buildworkdir
  - hostPath:
      path: /var/run/docker.sock
      type: ""
    name: docker-socket
  - hostPath:
      path: /var/run/crio/crio.sock
      type: ""
    name: crio-socket
  - name: builder-dockercfg-dhxm4-push
    secret:
      defaultMode: 384
      secretName: builder-dockercfg-dhxm4
  - name: builder-token-rfvmh
    secret:
      defaultMode: 420
      secretName: builder-token-rfvmh
status:
  phase: Pending
  qosClass: BestEffort
