apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: tomcat
    openshift.io/deployment.name: tomcat-1
    openshift.io/generated-by: OpenShiftWebConsole
    openshift.io/scc: restricted
  creationTimestamp: null
  generateName: tomcat-1-
  labels:
    app: tomcat
    deployment: tomcat-1
    deploymentconfig: tomcat
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: tomcat-1
    uid: df618373-ee3f-11e8-ba2b-0aa0c5b29fe8
spec:
  containers:
  - image: tomcat@sha256:6878215065a0bf6aec78ca133f0d1be6ff80f4ca52dd4fd53e7a246327223945
    imagePullPolicy: Always
    name: tomcat
    ports:
    - containerPort: 8080
      protocol: TCP
    resources: {}
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-kcgrz
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: default-dockercfg-mnwxn
  nodeName: amos01-compute001.amosdemo.io
  nodeSelector:
    node-role.kubernetes.io/compute: "true"
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    seLinuxOptions:
      level: s0:c11,c10
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: default-token-kcgrz
    secret:
      defaultMode: 420
      secretName: default-token-kcgrz
status:
  phase: Pending
  qosClass: BestEffort
