apiVersion: v1
kind: Project
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: ""
    openshift.io/requester: admin
    openshift.io/sa.scc.mcs: s0:c22,c19
    openshift.io/sa.scc.supplemental-groups: 1000500000/10000
    openshift.io/sa.scc.uid-range: 1000500000/10000
  creationTimestamp: null
  name: abcd
spec:
  finalizers:
  - openshift.io/origin
  - kubernetes
status:
  phase: Active
