apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    app: cakephp-mysql-persistent
    template: cakephp-mysql-persistent
  name: cakephp-mysql-persistent
subsets:
- notReadyAddresses:
  - ip: 10.131.0.205
    nodeName: amos01-compute001.amosdemo.io
    targetRef:
      kind: Pod
      name: cakephp-mysql-persistent-2-trz5l
      namespace: cloud-test
      resourceVersion: "5662207"
      uid: 4ebcd0dc-f30c-11e8-ba2b-0aa0c5b29fe8
  ports:
  - name: web
    port: 8080
    protocol: TCP
