apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    app: django-ex
  name: django-ex
subsets:
- addresses:
  - ip: 10.131.0.199
    nodeName: amos01-compute001.amosdemo.io
    targetRef:
      kind: Pod
      name: django-ex-1-w74wm
      namespace: cloud-test
      resourceVersion: "5628924"
      uid: 4ec18d19-f30c-11e8-ba2b-0aa0c5b29fe8
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
