apiVersion: v1
kind: Project
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: test1
    openshift.io/requester: admin
    openshift.io/sa.scc.mcs: s0:c13,c2
    openshift.io/sa.scc.supplemental-groups: 1000160000/10000
    openshift.io/sa.scc.uid-range: 1000160000/10000
  creationTimestamp: null
  name: test1
spec:
  finalizers:
  - openshift.io/origin
  - kubernetes
status:
  phase: Active
