apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    logging-infra: support
  name: logging-kibana
subsets:
- addresses:
  - ip: 10.129.0.83
    nodeName: amos01-infra001.amosdemo.io
    targetRef:
      kind: Pod
      name: logging-kibana-1-fwl2m
      namespace: logging
      resourceVersion: "3588341"
      uid: 92a0d3c3-ee20-11e8-ba2b-0aa0c5b29fe8
  ports:
  - port: 3000
    protocol: TCP
