apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  name: wlpdemo
spec:
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        pipeline {
          agent { label "maven" }
          stages {
            stage("Clone Source") {
              steps {
                  git credentialsId: 'wlp-git-repo-cred', url: 'https://github.gsissc.myatos.net/A164545/demo.git'
              }
            }
            stage('Code Analysis') {
                steps {
                  script {
                    sh 'mvn sonar:sonar -Dsonar.host.url=http://sonarqube.sonarqube.svc:9000 -DskipTests=true'
                  }
                }
              }
            stage("Build WAR") {
              steps {
                  sh 'mvn clean install'
              }
            }
            stage("Build Image") {
              steps {
                   sh 'oc start-build wlpapp --from-dir ./webs/web/target/war --follow'
               }
            }
          }
        }
    type: JenkinsPipeline
  triggers: []
status:
  lastVersion: 0
