apiVersion: v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
    template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
  creationTimestamp: null
  labels:
    app: sonarqube-ephemeral
    template: sonarqube-ephemeral-template
  name: sonar
spec:
  host: sonar-test1.apps01.amosdemo.io
  to:
    kind: Service
    name: sonar
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: 2018-12-01T16:03:59Z
      status: "True"
      type: Admitted
    host: sonar-test1.apps01.amosdemo.io
    routerName: router
    wildcardPolicy: None
