apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: CI/CD
    openshift.io/requester: admin
    openshift.io/sa.scc.mcs: s0:c11,c10
    openshift.io/sa.scc.supplemental-groups: 1000130000/10000
    openshift.io/sa.scc.uid-range: 1000130000/10000
  creationTimestamp: null
  name: cicd
spec:
  finalizers:
  - openshift.io/origin
  - kubernetes
status:
  phase: Active
