apiVersion: v1
groupNames: null
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    app: jenkins-persistent
    template: jenkins-persistent-template
  name: jenkins_edit
roleRef:
  name: edit
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: cicd
userNames:
- system:serviceaccount:cicd:jenkins
