apiVersion: v1
groupNames: null
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: system:deployer
roleRef:
  name: system:deployer
subjects:
- kind: ServiceAccount
  name: deployer
  namespace: svbtest
userNames:
- system:serviceaccount:svbtest:deployer
