apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes Heketi service
  creationTimestamp: null
  labels:
    glusterfs: heketi-storage-service
    heketi: storage-service
  name: heketi-storage
spec:
  ports:
  - name: heketi
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    glusterfs: heketi-storage-pod
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
