apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "1936"
    prometheus.io/scrape: "true"
    prometheus.openshift.io/password: 9ifmFneaCu
    prometheus.openshift.io/username: admin
    service.alpha.openshift.io/serving-cert-secret-name: router-certs
    service.alpha.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1540898865
  creationTimestamp: null
  labels:
    router: router
  name: router
spec:
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  - name: 443-tcp
    port: 443
    protocol: TCP
    targetPort: 443
  - name: 1936-tcp
    port: 1936
    protocol: TCP
    targetPort: 1936
  selector:
    router: router
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
