apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"16fbb61d-e7f0-11e8-8906-0a580a80005c","leaseDurationSeconds":15,"acquireTime":"2018-11-22T07:10:55Z","renewTime":"2018-11-22T07:10:59Z","leaderTransitions":0}'
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-class: glusterblock-storage
    volume.beta.kubernetes.io/storage-provisioner: gluster.org/glusterblock
  creationTimestamp: null
  name: logging-es-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  volumeName: pvc-c138c54b-ee25-11e8-ba2b-0aa0c5b29fe8
status: {}
