apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    openshift.io/deployer-pod.completed-at: 2018-11-27 11:32:04 +0000 UTC
    openshift.io/deployer-pod.created-at: 2018-11-27 11:33:32 +0000 UTC
    openshift.io/deployer-pod.name: cakephp-ex-2-deploy
    openshift.io/deployment-config.latest-version: "2"
    openshift.io/deployment-config.name: cakephp-ex
    openshift.io/deployment.phase: Complete
    openshift.io/deployment.replicas: "1"
    openshift.io/deployment.status-reason: image change
    openshift.io/encoded-deployment-config: |
      {"kind":"DeploymentConfig","apiVersion":"v1","metadata":{"name":"cakephp-ex","namespace":"abcd","selfLink":"/apis/apps.openshift.io/v1/namespaces/abcd/deploymentconfigs/cakephp-ex","uid":"dfb7b0f1-f237-11e8-ba2b-0aa0c5b29fe8","resourceVersion":"4439767","generation":3,"creationTimestamp":"2018-11-27T11:30:42Z","labels":{"app":"cakephp-ex"},"annotations":{"openshift.io/generated-by":"OpenShiftWebConsole"}},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["cakephp-ex"],"from":{"kind":"ImageStreamTag","namespace":"abcd","name":"cakephp-ex:latest"},"lastTriggeredImage":"docker-registry.default.svc:5000/abcd/cakephp-ex@sha256:9ef51818db9d669282090be9e700b3041b824218db67b243cb294da746150abd"}},{"type":"ConfigChange"}],"replicas":1,"test":false,"selector":{"deploymentconfig":"cakephp-ex"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"cakephp-ex","deploymentconfig":"cakephp-ex"}},"spec":{"containers":[{"name":"cakephp-ex","image":"docker-registry.default.svc:5000/abcd/cakephp-ex@sha256:9ef51818db9d669282090be9e700b3041b824218db67b243cb294da746150abd","ports":[{"containerPort":8080,"protocol":"TCP"},{"containerPort":8443,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":2,"observedGeneration":2,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"image change","causes":[{"type":"ImageChange","imageTrigger":{"from":{"kind":"DockerImage","name":"docker-registry.default.svc:5000/abcd/cakephp-ex@sha256:9ef51818db9d669282090be9e700b3041b824218db67b243cb294da746150abd"}}}]},"conditions":[{"type":"Available","status":"False","lastUpdateTime":"2018-11-27T11:30:42Z","lastTransitionTime":"2018-11-27T11:30:42Z","message":"Deployment config does not have minimum availability."},{"type":"Progressing","status":"Unknown","lastUpdateTime":"2018-11-27T11:32:30Z","lastTransitionTime":"2018-11-27T11:32:30Z","message":"replication controller \"cakephp-ex-1\" is waiting for pod \"cakephp-ex-1-deploy\" to run"}]}}
  creationTimestamp: null
  generation: 1
  labels:
    app: cakephp-ex
    openshift.io/deployment-config.name: cakephp-ex
  name: cakephp-ex-2
  ownerReferences:
  - apiVersion: apps.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: DeploymentConfig
    name: cakephp-ex
    uid: dfb7b0f1-f237-11e8-ba2b-0aa0c5b29fe8
spec:
  replicas: 2
  selector:
    deployment: cakephp-ex-2
    deploymentconfig: cakephp-ex
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: "2"
        openshift.io/deployment-config.name: cakephp-ex
        openshift.io/deployment.name: cakephp-ex-2
      creationTimestamp: null
      labels:
        app: cakephp-ex
        deployment: cakephp-ex-2
        deploymentconfig: cakephp-ex
    spec:
      containers:
      - image: docker-registry.default.svc:5000/abcd/cakephp-ex@sha256:9ef51818db9d669282090be9e700b3041b824218db67b243cb294da746150abd
        imagePullPolicy: Always
        name: cakephp-ex
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  replicas: 0
