apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kubectl.kubernetes.io/desired-replicas: "1"
    openshift.io/deployer-pod.created-at: 2018-11-30 11:40:46 +0000 UTC
    openshift.io/deployer-pod.name: ruby-ex-1-deploy
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: ruby-ex
    openshift.io/deployment.cancelled: "true"
    openshift.io/deployment.phase: Failed
    openshift.io/deployment.replicas: "0"
    openshift.io/deployment.status-reason: newer deployment was found running
    openshift.io/encoded-deployment-config: |
      {"kind":"DeploymentConfig","apiVersion":"v1","metadata":{"name":"ruby-ex","namespace":"abcd","selfLink":"/apis/apps.openshift.io/v1/namespaces/abcd/deploymentconfigs/ruby-ex","uid":"bc22b676-f494-11e8-ba2b-0aa0c5b29fe8","resourceVersion":"4969790","generation":2,"creationTimestamp":"2018-11-30T11:40:28Z","labels":{"app":"ruby-ex"},"annotations":{"openshift.io/generated-by":"OpenShiftWebConsole"}},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["ruby-ex"],"from":{"kind":"ImageStreamTag","namespace":"abcd","name":"ruby-ex:latest"},"lastTriggeredImage":"172.30.226.6:5000/abcd/ruby-ex@sha256:f5f607d0d18bd1f4b0f25fc3a8e07652c44f83f466774b46e5d87572652e0386"}},{"type":"ConfigChange"}],"replicas":1,"test":false,"selector":{"deploymentconfig":"ruby-ex"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"ruby-ex","deploymentconfig":"ruby-ex"}},"spec":{"containers":[{"name":"ruby-ex","image":"172.30.226.6:5000/abcd/ruby-ex@sha256:f5f607d0d18bd1f4b0f25fc3a8e07652c44f83f466774b46e5d87572652e0386","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":1,"observedGeneration":1,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"config change","causes":[{"type":"ConfigChange"}]},"conditions":[{"type":"Available","status":"False","lastUpdateTime":"2018-11-30T11:40:28Z","lastTransitionTime":"2018-11-30T11:40:28Z","message":"Deployment config does not have minimum availability."}]}}
  creationTimestamp: null
  generation: 1
  labels:
    app: ruby-ex
    openshift.io/deployment-config.name: ruby-ex
  name: ruby-ex-1
  ownerReferences:
  - apiVersion: apps.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: DeploymentConfig
    name: ruby-ex
    uid: bc22b676-f494-11e8-ba2b-0aa0c5b29fe8
spec:
  replicas: 0
  selector:
    deployment: ruby-ex-1
    deploymentconfig: ruby-ex
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: "1"
        openshift.io/deployment-config.name: ruby-ex
        openshift.io/deployment.name: ruby-ex-1
      creationTimestamp: null
      labels:
        app: ruby-ex
        deployment: ruby-ex-1
        deploymentconfig: ruby-ex
    spec:
      containers:
      - image: 172.30.226.6:5000/abcd/ruby-ex@sha256:f5f607d0d18bd1f4b0f25fc3a8e07652c44f83f466774b46e5d87572652e0386
        imagePullPolicy: Always
        name: ruby-ex
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  replicas: 0
