apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kubectl.kubernetes.io/desired-replicas: "1"
    kubectl.kubernetes.io/update-source-id: registry-console-3:29ebb49e-e8b3-11e8-ba2b-0aa0c5b29fe8
    openshift.io/deployer-pod.completed-at: 2018-11-15 08:54:37 +0000 UTC
    openshift.io/deployer-pod.created-at: 2018-11-15 08:52:23 +0000 UTC
    openshift.io/deployer-pod.name: registry-console-4-deploy
    openshift.io/deployment-config.latest-version: "4"
    openshift.io/deployment-config.name: registry-console
    openshift.io/deployment.cancelled: "true"
    openshift.io/deployment.phase: Failed
    openshift.io/deployment.replicas: "0"
    openshift.io/deployment.status-reason: The deployment was cancelled by the user
    openshift.io/encoded-deployment-config: |
      {"kind":"DeploymentConfig","apiVersion":"v1","metadata":{"name":"registry-console","namespace":"default","selfLink":"/apis/apps.openshift.io/v1/namespaces/default/deploymentconfigs/registry-console","uid":"facd140d-dda0-11e8-b362-0aa0c5b29fe8","resourceVersion":"2100920","generation":4,"creationTimestamp":"2018-11-01T06:40:10Z","labels":{"app":"registry-console","createdBy":"registry-console-template","name":"registry-console"},"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"}},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ConfigChange"}],"replicas":1,"revisionHistoryLimit":10,"test":false,"selector":{"name":"registry-console"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"registry-console","name":"registry-console"},"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"}},"spec":{"volumes":[{"name":"volume-4vlhv","secret":{"secretName":"console-secret","defaultMode":420}}],"containers":[{"name":"registry-console","image":"registry.access.redhat.com/openshift3/registry-console:v3.9","ports":[{"containerPort":9090,"protocol":"TCP"}],"env":[{"name":"OPENSHIFT_OAUTH_PROVIDER_URL","value":"https://master01.amosdemo.io:8443"},{"name":"OPENSHIFT_OAUTH_CLIENT_ID","value":"cockpit-oauth-client"},{"name":"KUBERNETES_INSECURE","value":"false"},{"name":"COCKPIT_KUBE_INSECURE","value":"false"},{"name":"REGISTRY_ONLY","value":"true"},{"name":"REGISTRY_HOST","value":"docker-registry-default.apps01.amosdemo.io"}],"resources":{},"volumeMounts":[{"name":"volume-4vlhv","mountPath":"/etc/cockpit/ws-certs.d"}],"livenessProbe":{"httpGet":{"path":"/ping","port":9090,"scheme":"HTTP"},"initialDelaySeconds":10,"timeoutSeconds":5,"periodSeconds":10,"successThreshold":1,"failureThreshold":3},"readinessProbe":{"httpGet":{"path":"/ping","port":9090,"scheme":"HTTP"},"timeoutSeconds":5,"periodSeconds":10,"successThreshold":1,"failureThreshold":3},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","nodeSelector":{"node-role.kubernetes.io/master":"true"},"securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":4,"observedGeneration":4,"replicas":1,"updatedReplicas":0,"availableReplicas":1,"unavailableReplicas":0,"details":{"message":"config change","causes":[{"type":"ConfigChange"}]},"conditions":[{"type":"Available","status":"True","lastUpdateTime":"2018-11-14T09:31:37Z","lastTransitionTime":"2018-11-14T09:31:37Z","message":"Deployment config has minimum availability."},{"type":"Progressing","status":"False","lastUpdateTime":"2018-11-15T08:52:14Z","lastTransitionTime":"2018-11-15T08:52:14Z","reason":"ProgressDeadlineExceeded","message":"replication controller \"registry-console-4\" has failed progressing"}],"readyReplicas":1}}
  creationTimestamp: null
  generation: 1
  labels:
    app: registry-console
    createdBy: registry-console-template
    name: registry-console
    openshift.io/deployment-config.name: registry-console
  name: registry-console-4
  ownerReferences:
  - apiVersion: apps.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: DeploymentConfig
    name: registry-console
    uid: facd140d-dda0-11e8-b362-0aa0c5b29fe8
spec:
  replicas: 0
  selector:
    deployment: registry-console-4
    deploymentconfig: registry-console
    name: registry-console
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: "4"
        openshift.io/deployment-config.name: registry-console
        openshift.io/deployment.name: registry-console-4
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: registry-console
        deployment: registry-console-4
        deploymentconfig: registry-console
        name: registry-console
    spec:
      containers:
      - env:
        - name: OPENSHIFT_OAUTH_PROVIDER_URL
          value: https://master01.amosdemo.io:8443
        - name: OPENSHIFT_OAUTH_CLIENT_ID
          value: cockpit-oauth-client
        - name: KUBERNETES_INSECURE
          value: "false"
        - name: COCKPIT_KUBE_INSECURE
          value: "false"
        - name: REGISTRY_ONLY
          value: "true"
        - name: REGISTRY_HOST
          value: docker-registry-default.apps01.amosdemo.io
        image: registry.access.redhat.com/openshift3/registry-console:v3.9
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: registry-console
        ports:
        - containerPort: 9090
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 9090
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/cockpit/ws-certs.d
          name: volume-4vlhv
      dnsPolicy: ClusterFirst
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: volume-4vlhv
        secret:
          defaultMode: 420
          secretName: console-secret
status:
  replicas: 0
