apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    openshift.io/deployer-pod.completed-at: 2018-11-30 04:51:28 +0000 UTC
    openshift.io/deployer-pod.created-at: 2018-11-30 04:51:28 +0000 UTC
    openshift.io/deployer-pod.name: router-33-deploy
    openshift.io/deployment-config.latest-version: "33"
    openshift.io/deployment-config.name: router
    openshift.io/deployment.phase: Complete
    openshift.io/deployment.replicas: ""
    openshift.io/deployment.status-reason: config change
    openshift.io/encoded-deployment-config: |
      {"kind":"DeploymentConfig","apiVersion":"v1","metadata":{"name":"router","namespace":"default","selfLink":"/apis/apps.openshift.io/v1/namespaces/default/deploymentconfigs/router","uid":"73acc7dc-e7f8-11e8-b832-0aa0c5b29fe8","resourceVersion":"4917434","generation":45,"creationTimestamp":"2018-11-14T10:31:31Z","labels":{"router":"router"}},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":0},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ConfigChange"}],"replicas":1,"test":false,"selector":{"router":"router"},"template":{"metadata":{"creationTimestamp":null,"labels":{"router":"router"}},"spec":{"volumes":[{"name":"server-certificate","secret":{"secretName":"router-certs","defaultMode":420}},{"name":"custom-config-404","configMap":{"name":"haproxy-custom-404","defaultMode":420}},{"name":"custom-config-408","configMap":{"name":"haproxy-custom-408","defaultMode":420}},{"name":"custom-config-503","configMap":{"name":"haproxy-custom-503","defaultMode":420}},{"name":"custom-config-template","configMap":{"name":"haproxy-custom-template","defaultMode":420}}],"containers":[{"name":"router","image":"openshift3/ose-haproxy-router:v3.9.27","ports":[{"hostPort":80,"containerPort":80,"protocol":"TCP"},{"hostPort":443,"containerPort":443,"protocol":"TCP"},{"name":"stats","hostPort":1936,"containerPort":1936,"protocol":"TCP"}],"env":[{"name":"DEFAULT_CERTIFICATE_DIR","value":"/etc/pki/tls/private"},{"name":"DEFAULT_CERTIFICATE_PATH","value":"/etc/pki/tls/private/tls.crt"},{"name":"ROUTER_CIPHERS"},{"name":"ROUTER_EXTERNAL_HOST_HOSTNAME"},{"name":"ROUTER_EXTERNAL_HOST_HTTPS_VSERVER"},{"name":"ROUTER_EXTERNAL_HOST_HTTP_VSERVER"},{"name":"ROUTER_EXTERNAL_HOST_INSECURE","value":"false"},{"name":"ROUTER_EXTERNAL_HOST_INTERNAL_ADDRESS"},{"name":"ROUTER_EXTERNAL_HOST_PARTITION_PATH"},{"name":"ROUTER_EXTERNAL_HOST_PASSWORD"},{"name":"ROUTER_EXTERNAL_HOST_PRIVKEY","value":"/etc/secret-volume/router.pem"},{"name":"ROUTER_EXTERNAL_HOST_USERNAME"},{"name":"ROUTER_EXTERNAL_HOST_VXLAN_GW_CIDR"},{"name":"ROUTER_LISTEN_ADDR","value":"0.0.0.0:1936"},{"name":"ROUTER_METRICS_TYPE","value":"haproxy"},{"name":"ROUTER_SERVICE_HTTPS_PORT","value":"443"},{"name":"ROUTER_SERVICE_HTTP_PORT","value":"80"},{"name":"ROUTER_SERVICE_NAME","value":"router"},{"name":"ROUTER_SERVICE_NAMESPACE","value":"default"},{"name":"ROUTER_SUBDOMAIN"},{"name":"STATS_PASSWORD","value":"ND1TlJXqvZ"},{"name":"STATS_PORT","value":"1936"},{"name":"STATS_USERNAME","value":"admin"}],"resources":{"requests":{"cpu":"100m","memory":"256Mi"}},"volumeMounts":[{"name":"server-certificate","readOnly":true,"mountPath":"/etc/pki/tls/private"},{"name":"custom-config-404","mountPath":"/var/lib/haproxy/conf/error-page-404.http","subPath":"error-page-404.http"},{"name":"custom-config-408","mountPath":"/var/lib/haproxy/conf/error-page-408.http","subPath":"error-page-408.http"},{"name":"custom-config-503","mountPath":"/var/lib/haproxy/conf/error-page-503.http","subPath":"error-page-503.http"},{"name":"custom-config-template","mountPath":"/var/lib/haproxy/conf/haproxy-config.template","subPath":"haproxy-config.template"}],"livenessProbe":{"httpGet":{"path":"/healthz","port":1936,"host":"localhost","scheme":"HTTP"},"initialDelaySeconds":10,"timeoutSeconds":1,"periodSeconds":10,"successThreshold":1,"failureThreshold":3},"readinessProbe":{"httpGet":{"path":"/healthz","port":1936,"host":"localhost","scheme":"HTTP"},"initialDelaySeconds":10,"timeoutSeconds":1,"periodSeconds":10,"successThreshold":1,"failureThreshold":3},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","nodeSelector":{"region":"infra"},"serviceAccountName":"router","serviceAccount":"router","hostNetwork":true,"securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":33,"observedGeneration":44,"replicas":1,"updatedReplicas":1,"availableReplicas":0,"unavailableReplicas":1,"details":{"message":"config change","causes":[{"type":"ConfigChange"}]},"conditions":[{"type":"Available","status":"False","lastUpdateTime":"2018-11-30T04:51:00Z","lastTransitionTime":"2018-11-30T04:51:00Z","message":"Deployment config does not have minimum availability."},{"type":"Progressing","status":"True","lastUpdateTime":"2018-11-30T04:51:24Z","lastTransitionTime":"2018-11-30T04:51:22Z","reason":"NewReplicationControllerAvailable","message":"replication controller \"router-32\" successfully rolled out"}]}}
  creationTimestamp: null
  generation: 1
  labels:
    openshift.io/deployment-config.name: router
    router: router
  name: router-33
  ownerReferences:
  - apiVersion: apps.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: DeploymentConfig
    name: router
    uid: 73acc7dc-e7f8-11e8-b832-0aa0c5b29fe8
spec:
  replicas: 1
  selector:
    deployment: router-33
    deploymentconfig: router
    router: router
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: "33"
        openshift.io/deployment-config.name: router
        openshift.io/deployment.name: router-33
      creationTimestamp: null
      labels:
        deployment: router-33
        deploymentconfig: router
        router: router
    spec:
      containers:
      - env:
        - name: DEFAULT_CERTIFICATE_DIR
          value: /etc/pki/tls/private
        - name: DEFAULT_CERTIFICATE_PATH
          value: /etc/pki/tls/private/tls.crt
        - name: ROUTER_CIPHERS
        - name: ROUTER_EXTERNAL_HOST_HOSTNAME
        - name: ROUTER_EXTERNAL_HOST_HTTPS_VSERVER
        - name: ROUTER_EXTERNAL_HOST_HTTP_VSERVER
        - name: ROUTER_EXTERNAL_HOST_INSECURE
          value: "false"
        - name: ROUTER_EXTERNAL_HOST_INTERNAL_ADDRESS
        - name: ROUTER_EXTERNAL_HOST_PARTITION_PATH
        - name: ROUTER_EXTERNAL_HOST_PASSWORD
        - name: ROUTER_EXTERNAL_HOST_PRIVKEY
          value: /etc/secret-volume/router.pem
        - name: ROUTER_EXTERNAL_HOST_USERNAME
        - name: ROUTER_EXTERNAL_HOST_VXLAN_GW_CIDR
        - name: ROUTER_LISTEN_ADDR
          value: 0.0.0.0:1936
        - name: ROUTER_METRICS_TYPE
          value: haproxy
        - name: ROUTER_SERVICE_HTTPS_PORT
          value: "443"
        - name: ROUTER_SERVICE_HTTP_PORT
          value: "80"
        - name: ROUTER_SERVICE_NAME
          value: router
        - name: ROUTER_SERVICE_NAMESPACE
          value: default
        - name: ROUTER_SUBDOMAIN
        - name: STATS_PASSWORD
          value: ND1TlJXqvZ
        - name: STATS_PORT
          value: "1936"
        - name: STATS_USERNAME
          value: admin
        image: openshift3/ose-haproxy-router:v3.9.27
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            host: localhost
            path: /healthz
            port: 1936
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: router
        ports:
        - containerPort: 80
          hostPort: 80
          protocol: TCP
        - containerPort: 443
          hostPort: 443
          protocol: TCP
        - containerPort: 1936
          hostPort: 1936
          name: stats
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            host: localhost
            path: /healthz
            port: 1936
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/pki/tls/private
          name: server-certificate
          readOnly: true
        - mountPath: /var/lib/haproxy/conf/error-page-404.http
          name: custom-config-404
          subPath: error-page-404.http
        - mountPath: /var/lib/haproxy/conf/error-page-408.http
          name: custom-config-408
          subPath: error-page-408.http
        - mountPath: /var/lib/haproxy/conf/error-page-503.http
          name: custom-config-503
          subPath: error-page-503.http
        - mountPath: /var/lib/haproxy/conf/haproxy-config.template
          name: custom-config-template
          subPath: haproxy-config.template
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        region: infra
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: router
      serviceAccountName: router
      terminationGracePeriodSeconds: 30
      volumes:
      - name: server-certificate
        secret:
          defaultMode: 420
          secretName: router-certs
      - configMap:
          defaultMode: 420
          name: haproxy-custom-404
        name: custom-config-404
      - configMap:
          defaultMode: 420
          name: haproxy-custom-408
        name: custom-config-408
      - configMap:
          defaultMode: 420
          name: haproxy-custom-503
        name: custom-config-503
      - configMap:
          defaultMode: 420
          name: haproxy-custom-template
        name: custom-config-template
status:
  replicas: 0
