apiVersion: v1
groupNames: null
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: system:image-builders
roleRef:
  name: system:image-builder
subjects:
- kind: ServiceAccount
  name: builder
  namespace: achaitanya1
userNames:
- system:serviceaccount:achaitanya1:builder
