apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kubectl.kubernetes.io/desired-replicas: "1"
    openshift.io/deployer-pod.completed-at: 2018-12-04 09:19:12 +0000 UTC
    openshift.io/deployer-pod.created-at: 2018-12-04 09:11:04 +0000 UTC
    openshift.io/deployer-pod.name: database-1-deploy
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: database
    openshift.io/deployment.phase: Failed
    openshift.io/deployment.replicas: "0"
    openshift.io/deployment.status-reason: config change
    openshift.io/encoded-deployment-config: |
      {"kind":"DeploymentConfig","apiVersion":"v1","metadata":{"name":"database","namespace":"demokt","selfLink":"/apis/apps.openshift.io/v1/namespaces/demokt/deploymentconfigs/database","uid":"86de4a55-f7a4-11e8-ba2b-0aa0c5b29fe8","resourceVersion":"5656901","generation":2,"creationTimestamp":"2018-12-04T09:11:04Z","labels":{"app":"dancer-mysql-example","template":"dancer-mysql-example"},"annotations":{"description":"Defines how to deploy the database","template.alpha.openshift.io/wait-for-ready":"true"}},"spec":{"strategy":{"type":"Recreate","recreateParams":{"timeoutSeconds":600},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["mysql"],"from":{"kind":"ImageStreamTag","namespace":"openshift","name":"mysql:5.7"},"lastTriggeredImage":"registry.access.redhat.com/rhscl/mysql-57-rhel7@sha256:d1b66e8759a2952627e5009d62e82c2aad6a265f85fd4661e04de70e75a59e37"}},{"type":"ConfigChange"}],"replicas":1,"test":false,"selector":{"name":"database"},"template":{"metadata":{"name":"database","creationTimestamp":null,"labels":{"name":"database"}},"spec":{"volumes":[{"name":"data","emptyDir":{}}],"containers":[{"name":"mysql","image":"registry.access.redhat.com/rhscl/mysql-57-rhel7@sha256:d1b66e8759a2952627e5009d62e82c2aad6a265f85fd4661e04de70e75a59e37","ports":[{"containerPort":3306,"protocol":"TCP"}],"env":[{"name":"MYSQL_USER","valueFrom":{"secretKeyRef":{"name":"dancer-mysql-example","key":"database-user"}}},{"name":"MYSQL_PASSWORD","valueFrom":{"secretKeyRef":{"name":"dancer-mysql-example","key":"database-password"}}},{"name":"MYSQL_DATABASE","value":"sampledb"}],"resources":{"limits":{"memory":"512Mi"}},"volumeMounts":[{"name":"data","mountPath":"/var/lib/mysql/data"}],"livenessProbe":{"tcpSocket":{"port":3306},"initialDelaySeconds":30,"timeoutSeconds":1,"periodSeconds":10,"successThreshold":1,"failureThreshold":3},"readinessProbe":{"exec":{"command":["/bin/sh","-i","-c","MYSQL_PWD='wTELLTlr' mysql -h 127.0.0.1 -u userF7E -D sampledb -e 'SELECT 1'"]},"initialDelaySeconds":5,"timeoutSeconds":1,"periodSeconds":10,"successThreshold":1,"failureThreshold":3},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":1,"observedGeneration":0,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"config change","causes":[{"type":"ConfigChange"}]}}}
  creationTimestamp: null
  generation: 1
  labels:
    app: dancer-mysql-example
    openshift.io/deployment-config.name: database
    template: dancer-mysql-example
  name: database-1
  ownerReferences:
  - apiVersion: apps.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: DeploymentConfig
    name: database
    uid: 86de4a55-f7a4-11e8-ba2b-0aa0c5b29fe8
spec:
  replicas: 0
  selector:
    deployment: database-1
    deploymentconfig: database
    name: database
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: "1"
        openshift.io/deployment-config.name: database
        openshift.io/deployment.name: database-1
      creationTimestamp: null
      labels:
        deployment: database-1
        deploymentconfig: database
        name: database
    spec:
      containers:
      - env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: dancer-mysql-example
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: dancer-mysql-example
        - name: MYSQL_DATABASE
          value: sampledb
        image: registry.access.redhat.com/rhscl/mysql-57-rhel7@sha256:d1b66e8759a2952627e5009d62e82c2aad6a265f85fd4661e04de70e75a59e37
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3306
          timeoutSeconds: 1
        name: mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - MYSQL_PWD='wTELLTlr' mysql -h 127.0.0.1 -u userF7E -D sampledb -e 'SELECT
              1'
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql/data
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: data
status:
  replicas: 0
