apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/deployment-config.latest-version: "2"
    openshift.io/deployment-config.name: cakephp-mysql-persistent
    openshift.io/deployment.name: cakephp-mysql-persistent-2
    openshift.io/scc: restricted
  creationTimestamp: null
  generateName: cakephp-mysql-persistent-2-
  labels:
    deployment: cakephp-mysql-persistent-2
    deploymentconfig: cakephp-mysql-persistent
    name: cakephp-mysql-persistent
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: cakephp-mysql-persistent-2
    uid: c0e68a27-ebe7-11e8-ba2b-0aa0c5b29fe8
spec:
  containers:
  - env:
    - name: DATABASE_SERVICE_NAME
      value: mysql
    - name: DATABASE_ENGINE
      value: mysql
    - name: DATABASE_NAME
      value: default
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          key: database-user
          name: cakephp-mysql-persistent
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: database-password
          name: cakephp-mysql-persistent
    - name: CAKEPHP_SECRET_TOKEN
      valueFrom:
        secretKeyRef:
          key: cakephp-secret-token
          name: cakephp-mysql-persistent
    - name: CAKEPHP_SECURITY_SALT
      valueFrom:
        secretKeyRef:
          key: cakephp-security-salt
          name: cakephp-mysql-persistent
    - name: CAKEPHP_SECURITY_CIPHER_SEED
      valueFrom:
        secretKeyRef:
          key: cakephp-security-cipher-seed
          name: cakephp-mysql-persistent
    - name: OPCACHE_REVALIDATE_FREQ
      value: "2"
    image: docker-registry.default.svc:5000/cloud-test/cakephp-mysql-persistent@sha256:4b81316236687c001a2c1afa2b2b4b7db412dca8264c378217700946509d0fef
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health.php
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 3
    name: cakephp-mysql-persistent
    ports:
    - containerPort: 8080
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health.php
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 3
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 3
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 512Mi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-thtvp
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: default-dockercfg-j64zk
  nodeName: amos01-compute001.amosdemo.io
  nodeSelector:
    node-role.kubernetes.io/compute: "true"
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    seLinuxOptions:
      level: s0:c17,c9
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: default-token-thtvp
    secret:
      defaultMode: 420
      secretName: default-token-thtvp
status:
  phase: Pending
  qosClass: Burstable
