apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: ""
    openshift.io/requester: system:admin
    openshift.io/sa.scc.mcs: s0:c21,c20
    openshift.io/sa.scc.supplemental-groups: 1000460000/10000
    openshift.io/sa.scc.uid-range: 1000460000/10000
  creationTimestamp: null
  name: develop
spec:
  finalizers:
  - openshift.io/origin
  - kubernetes
status:
  phase: Active
