apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes the database server
  creationTimestamp: null
  labels:
    app: gogs
  name: gogs-postgresql
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: gogs-postgresql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
