apiVersion: v1
groupNames:
- system:serviceaccounts:cloud-test
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: system:image-pullers
roleRef:
  name: system:image-puller
subjects:
- kind: SystemGroup
  name: system:serviceaccounts:cloud-test
userNames: null
