apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    app: testphpapplication
  name: testphpapplication
subsets:
- addresses:
  - ip: 10.131.1.81
    nodeName: amos01-compute001.amosdemo.io
    targetRef:
      kind: Pod
      name: testphpapplication-2-55mmx
      namespace: achaitanya1
      resourceVersion: "5629015"
      uid: a9546cd1-f47d-11e8-ba2b-0aa0c5b29fe8
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
