apiVersion: v1
groupNames: null
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    app: jenkins-ephemeral
    template: jenkins-ephemeral-template
  name: jenkins_edit
roleRef:
  name: edit
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: glusterfs
userNames:
- system:serviceaccount:glusterfs:jenkins
