apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    gluster.kubernetes.io/provisioned-for-pvc: myapp-postgresql-claim
  name: glusterfs-dynamic-myapp-postgresql-claim
spec:
  ports:
  - port: 1
    protocol: TCP
    targetPort: 1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
