apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The database server's port.
  creationTimestamp: null
  labels:
    app: eap70-postgresql-persistent-s2i
    application: myapp
    template: eap70-postgresql-persistent-s2i
    xpaas: 1.4.14
  name: myapp-postgresql
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    deploymentConfig: myapp-postgresql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
