apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The JGroups ping port for clustering.
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  creationTimestamp: null
  labels:
    app: eap70-postgresql-persistent-s2i
    application: myapp
    template: eap70-postgresql-persistent-s2i
    xpaas: 1.4.14
  name: myapp-ping
spec:
  clusterIP: None
  ports:
  - name: ping
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    deploymentConfig: myapp
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
