apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's https port.
    service.alpha.openshift.io/dependencies: '[{"name": "myapp-postgresql", "kind":
      "Service"}]'
  creationTimestamp: null
  labels:
    app: eap70-postgresql-persistent-s2i
    application: myapp
    template: eap70-postgresql-persistent-s2i
    xpaas: 1.4.14
  name: secure-myapp
spec:
  ports:
  - port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    deploymentConfig: myapp
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
