apiVersion: v1
kind: Template
metadata:
  annotations:
    description: Heketi service deployment template
    tags: glusterfs,heketi
  creationTimestamp: null
  labels:
    glusterfs: heketi-template
  name: heketi
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes Heketi service
    labels:
      glusterfs: heketi-${CLUSTER_NAME}-service
      heketi: ${CLUSTER_NAME}-service
    name: heketi-${CLUSTER_NAME}
  spec:
    ports:
    - name: heketi
      port: 8080
      targetPort: 8080
    selector:
      glusterfs: heketi-${CLUSTER_NAME}-pod
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      glusterfs: heketi-${CLUSTER_NAME}-route
      heketi: ${CLUSTER_NAME}-route
    name: ${HEKETI_ROUTE}
  spec:
    to:
      kind: Service
      name: heketi-${CLUSTER_NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy Heketi
    labels:
      glusterfs: heketi-${CLUSTER_NAME}-dc
      heketi: ${CLUSTER_NAME}-dc
    name: heketi-${CLUSTER_NAME}
  spec:
    replicas: 1
    selector:
      glusterfs: heketi-${CLUSTER_NAME}-pod
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          glusterfs: heketi-${CLUSTER_NAME}-pod
          heketi: ${CLUSTER_NAME}-pod
        name: heketi-${CLUSTER_NAME}
      spec:
        containers:
        - env:
          - name: HEKETI_USER_KEY
            value: ${HEKETI_USER_KEY}
          - name: HEKETI_ADMIN_KEY
            value: ${HEKETI_ADMIN_KEY}
          - name: HEKETI_EXECUTOR
            value: ${HEKETI_EXECUTOR}
          - name: HEKETI_FSTAB
            value: ${HEKETI_FSTAB}
          - name: HEKETI_SNAPSHOT_LIMIT
            value: "14"
          - name: HEKETI_KUBE_GLUSTER_DAEMONSET
            value: "1"
          - name: HEKETI_IGNORE_STALE_OPERATIONS
            value: "true"
          image: ${IMAGE_NAME}:${IMAGE_VERSION}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /hello
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 3
          name: heketi
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /hello
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 3
          volumeMounts:
          - mountPath: /var/lib/heketi
            name: db
          - mountPath: /etc/heketi
            name: config
        serviceAccountName: heketi-${CLUSTER_NAME}-service-account
        volumes:
        - glusterfs:
            endpoints: heketi-db-${CLUSTER_NAME}-endpoints
            path: heketidbstorage
          name: db
        - name: config
          secret:
            secretName: heketi-${CLUSTER_NAME}-config-secret
    triggers:
    - type: ConfigChange
parameters:
- description: Set secret for those creating volumes as type _user_
  displayName: Heketi User Secret
  name: HEKETI_USER_KEY
- description: Set secret for administration of the Heketi service as user _admin_
  displayName: Heketi Administrator Secret
  name: HEKETI_ADMIN_KEY
- description: Set the executor type, kubernetes or ssh
  displayName: heketi executor type
  name: HEKETI_EXECUTOR
  value: kubernetes
- description: Set the fstab path, file that is populated with bricks that heketi
    creates
  displayName: heketi fstab path
  name: HEKETI_FSTAB
  value: /var/lib/heketi/fstab
- description: Set the hostname for the route URL
  displayName: heketi route name
  name: HEKETI_ROUTE
  value: heketi-glusterfs
- displayName: heketi container image name
  name: IMAGE_NAME
  required: true
- displayName: heketi container image version
  name: IMAGE_VERSION
  required: true
- description: A unique name to identify this heketi service, useful for running multiple
    heketi instances
  displayName: GlusterFS cluster name
  name: CLUSTER_NAME
  value: glusterfs
