apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: eap70-postgresql-persistent-s2i
    application: myapp
    template: eap70-postgresql-persistent-s2i
    xpaas: 1.4.14
  name: myapp
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: myapp:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: todolist/todolist-jdbc
    git:
      ref: "1.3"
      uri: https://github.com/jboss-openshift/openshift-quickstarts
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: MAVEN_MIRROR_URL
      - name: ARTIFACT_DIR
      forcePull: true
      from:
        kind: ImageStreamTag
        name: jboss-eap70-openshift:1.7
        namespace: openshift
    type: Source
  triggers:
  - github:
      secret: Sld8YqcC
    type: GitHub
  - generic:
      secret: Yb8q6sQM
    type: Generic
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
status:
  lastVersion: 0
