apiVersion: v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    glusterblock: provisioner-runner-clusterrole
    glusterfs: block-provisioner-runner-clusterrole
  name: glusterblock-provisioner-runner
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - persistentvolumes
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - storage.k8s.io
  attributeRestrictions: null
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - events
  verbs:
  - create
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - services
  verbs:
  - get
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - routes
  verbs:
  - get
  - list
