apiVersion: v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ClusterRole","metadata":{"annotations":{},"labels":{"metrics-infra":"hawkular-metrics"},"name":"hawkular-metrics","namespace":""},"rules":[{"apiGroups":[""],"resources":["namespaces"],"verbs":["list","get","watch"]}]}
  creationTimestamp: null
  labels:
    metrics-infra: hawkular-metrics
  name: hawkular-metrics
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
