apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    metrics-infra: heapster
    name: heapster
  name: heapster
subsets:
- addresses:
  - ip: 10.128.0.136
    nodeName: amos01-master001.amosdemo.io
    targetRef:
      kind: Pod
      name: heapster-8qbc9
      namespace: openshift-infra
      resourceVersion: "5380844"
      uid: 13c80b9f-ed67-11e8-ba2b-0aa0c5b29fe8
  ports:
  - port: 8082
    protocol: TCP
