apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/deployment-config.latest-version: "2"
    openshift.io/deployment-config.name: django-ex
    openshift.io/deployment.name: django-ex-2
    openshift.io/scc: anyuid
  creationTimestamp: null
  generateName: django-ex-2-
  labels:
    app: django-ex
    deployment: django-ex-2
    deploymentconfig: django-ex
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: django-ex-2
    uid: dd490cda-f3ba-11e8-ba2b-0aa0c5b29fe8
spec:
  containers:
  - image: docker-registry.default.svc:5000/abcd/django-ex@sha256:5a6035417039334a57ffa323ccdbb4e44e076123d3e01f1a26eea8088e2ee66f
    imagePullPolicy: Always
    name: django-ex
    ports:
    - containerPort: 8080
      protocol: TCP
    resources: {}
    securityContext:
      capabilities:
        drop:
        - MKNOD
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-xmwqt
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: default-dockercfg-hskql
  nodeName: amos01-compute001.amosdemo.io
  nodeSelector:
    node-role.kubernetes.io/compute: "true"
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    seLinuxOptions:
      level: s0:c22,c19
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: default-token-xmwqt
    secret:
      defaultMode: 420
      secretName: default-token-xmwqt
status:
  phase: Pending
  qosClass: BestEffort
