apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/build.name: ruby-ex-1
    openshift.io/scc: privileged
  creationTimestamp: null
  labels:
    openshift.io/build.name: ruby-ex-1
  name: ruby-ex-1-build
  ownerReferences:
  - apiVersion: build.openshift.io/v1
    controller: true
    kind: Build
    name: ruby-ex-1
    uid: bc29fad3-f494-11e8-ba2b-0aa0c5b29fe8
spec:
  containers:
  - args:
    - --loglevel=0
    command:
    - openshift-sti-build
    env:
    - name: BUILD
      value: |
        {"kind":"Build","apiVersion":"v1","metadata":{"name":"ruby-ex-1","namespace":"abcd","selfLink":"/apis/build.openshift.io/v1/namespaces/abcd/builds/ruby-ex-1","uid":"bc29fad3-f494-11e8-ba2b-0aa0c5b29fe8","resourceVersion":"4969726","creationTimestamp":"2018-11-30T11:40:28Z","labels":{"app":"ruby-ex","buildconfig":"ruby-ex","openshift.io/build-config.name":"ruby-ex","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"ruby-ex","openshift.io/build.number":"1"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"ruby-ex","uid":"bc20ec82-f494-11e8-ba2b-0aa0c5b29fe8","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"https://github.com/openshift/ruby-ex.git","ref":"master"}},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"registry.access.redhat.com/rhscl/ruby-24-rhel7@sha256:76f6998c1e95a62ac460d19f2896a8c5ce365b863f6f293ead4faeb1c129ea9e"}}},"output":{"to":{"kind":"DockerImage","name":"docker-registry.default.svc:5000/abcd/ruby-ex:latest"},"pushSecret":{"name":"builder-dockercfg-82cl4"}},"resources":{},"postCommit":{},"nodeSelector":null,"triggeredBy":[{"message":"Image change","imageChangeBuild":{"imageID":"registry.access.redhat.com/rhscl/ruby-24-rhel7@sha256:76f6998c1e95a62ac460d19f2896a8c5ce365b863f6f293ead4faeb1c129ea9e","fromRef":{"kind":"ImageStreamTag","namespace":"openshift","name":"ruby:2.4"}}}]},"status":{"phase":"New","outputDockerImageReference":"docker-registry.default.svc:5000/abcd/ruby-ex:latest","config":{"kind":"BuildConfig","namespace":"abcd","name":"ruby-ex"},"output":{}}}
    - name: SOURCE_REPOSITORY
      value: https://github.com/openshift/ruby-ex.git
    - name: SOURCE_URI
      value: https://github.com/openshift/ruby-ex.git
    - name: SOURCE_REF
      value: master
    - name: ORIGIN_VERSION
      value: v3.9.27
    - name: ALLOWED_UIDS
      value: 1-
    - name: DROP_CAPS
      value: KILL,MKNOD,SETGID,SETUID
    - name: PUSH_DOCKERCFG_PATH
      value: /var/run/secrets/openshift.io/push
    image: openshift3/ose-sti-builder:v3.9.27
    imagePullPolicy: IfNotPresent
    name: sti-build
    resources: {}
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp/build
      name: buildworkdir
    - mountPath: /var/run/docker.sock
      name: docker-socket
    - mountPath: /var/run/crio/crio.sock
      name: crio-socket
    - mountPath: /var/run/secrets/openshift.io/push
      name: builder-dockercfg-82cl4-push
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: builder-token-7sch6
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: builder-dockercfg-82cl4
  initContainers:
  - args:
    - --loglevel=0
    command:
    - openshift-git-clone
    env:
    - name: BUILD
      value: |
        {"kind":"Build","apiVersion":"v1","metadata":{"name":"ruby-ex-1","namespace":"abcd","selfLink":"/apis/build.openshift.io/v1/namespaces/abcd/builds/ruby-ex-1","uid":"bc29fad3-f494-11e8-ba2b-0aa0c5b29fe8","resourceVersion":"4969726","creationTimestamp":"2018-11-30T11:40:28Z","labels":{"app":"ruby-ex","buildconfig":"ruby-ex","openshift.io/build-config.name":"ruby-ex","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"ruby-ex","openshift.io/build.number":"1"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"ruby-ex","uid":"bc20ec82-f494-11e8-ba2b-0aa0c5b29fe8","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"https://github.com/openshift/ruby-ex.git","ref":"master"}},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"registry.access.redhat.com/rhscl/ruby-24-rhel7@sha256:76f6998c1e95a62ac460d19f2896a8c5ce365b863f6f293ead4faeb1c129ea9e"}}},"output":{"to":{"kind":"DockerImage","name":"docker-registry.default.svc:5000/abcd/ruby-ex:latest"},"pushSecret":{"name":"builder-dockercfg-82cl4"}},"resources":{},"postCommit":{},"nodeSelector":null,"triggeredBy":[{"message":"Image change","imageChangeBuild":{"imageID":"registry.access.redhat.com/rhscl/ruby-24-rhel7@sha256:76f6998c1e95a62ac460d19f2896a8c5ce365b863f6f293ead4faeb1c129ea9e","fromRef":{"kind":"ImageStreamTag","namespace":"openshift","name":"ruby:2.4"}}}]},"status":{"phase":"New","outputDockerImageReference":"docker-registry.default.svc:5000/abcd/ruby-ex:latest","config":{"kind":"BuildConfig","namespace":"abcd","name":"ruby-ex"},"output":{}}}
    - name: SOURCE_REPOSITORY
      value: https://github.com/openshift/ruby-ex.git
    - name: SOURCE_URI
      value: https://github.com/openshift/ruby-ex.git
    - name: SOURCE_REF
      value: master
    - name: ORIGIN_VERSION
      value: v3.9.27
    - name: ALLOWED_UIDS
      value: 1-
    - name: DROP_CAPS
      value: KILL,MKNOD,SETGID,SETUID
    image: openshift3/ose-sti-builder:v3.9.27
    imagePullPolicy: IfNotPresent
    name: git-clone
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp/build
      name: buildworkdir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: builder-token-7sch6
      readOnly: true
  - args:
    - --loglevel=0
    command:
    - openshift-manage-dockerfile
    env:
    - name: BUILD
      value: |
        {"kind":"Build","apiVersion":"v1","metadata":{"name":"ruby-ex-1","namespace":"abcd","selfLink":"/apis/build.openshift.io/v1/namespaces/abcd/builds/ruby-ex-1","uid":"bc29fad3-f494-11e8-ba2b-0aa0c5b29fe8","resourceVersion":"4969726","creationTimestamp":"2018-11-30T11:40:28Z","labels":{"app":"ruby-ex","buildconfig":"ruby-ex","openshift.io/build-config.name":"ruby-ex","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"ruby-ex","openshift.io/build.number":"1"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"ruby-ex","uid":"bc20ec82-f494-11e8-ba2b-0aa0c5b29fe8","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"https://github.com/openshift/ruby-ex.git","ref":"master"}},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"registry.access.redhat.com/rhscl/ruby-24-rhel7@sha256:76f6998c1e95a62ac460d19f2896a8c5ce365b863f6f293ead4faeb1c129ea9e"}}},"output":{"to":{"kind":"DockerImage","name":"docker-registry.default.svc:5000/abcd/ruby-ex:latest"},"pushSecret":{"name":"builder-dockercfg-82cl4"}},"resources":{},"postCommit":{},"nodeSelector":null,"triggeredBy":[{"message":"Image change","imageChangeBuild":{"imageID":"registry.access.redhat.com/rhscl/ruby-24-rhel7@sha256:76f6998c1e95a62ac460d19f2896a8c5ce365b863f6f293ead4faeb1c129ea9e","fromRef":{"kind":"ImageStreamTag","namespace":"openshift","name":"ruby:2.4"}}}]},"status":{"phase":"New","outputDockerImageReference":"docker-registry.default.svc:5000/abcd/ruby-ex:latest","config":{"kind":"BuildConfig","namespace":"abcd","name":"ruby-ex"},"output":{}}}
    - name: SOURCE_REPOSITORY
      value: https://github.com/openshift/ruby-ex.git
    - name: SOURCE_URI
      value: https://github.com/openshift/ruby-ex.git
    - name: SOURCE_REF
      value: master
    - name: ORIGIN_VERSION
      value: v3.9.27
    - name: ALLOWED_UIDS
      value: 1-
    - name: DROP_CAPS
      value: KILL,MKNOD,SETGID,SETUID
    image: openshift3/ose-sti-builder:v3.9.27
    imagePullPolicy: IfNotPresent
    name: manage-dockerfile
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp/build
      name: buildworkdir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: builder-token-7sch6
      readOnly: true
  nodeName: amos01-compute001.amosdemo.io
  nodeSelector:
    node-role.kubernetes.io/compute: "true"
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: builder
  serviceAccountName: builder
  terminationGracePeriodSeconds: 30
  volumes:
  - emptyDir: {}
    name: buildworkdir
  - hostPath:
      path: /var/run/docker.sock
      type: ""
    name: docker-socket
  - hostPath:
      path: /var/run/crio/crio.sock
      type: ""
    name: crio-socket
  - name: builder-dockercfg-82cl4-push
    secret:
      defaultMode: 384
      secretName: builder-dockercfg-82cl4
  - name: builder-token-7sch6
    secret:
      defaultMode: 420
      secretName: builder-token-7sch6
status:
  phase: Pending
  qosClass: BestEffort
