apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/deployment-config.latest-version: "2"
    openshift.io/deployment-config.name: ruby-ex
    openshift.io/deployment.name: ruby-ex-2
    openshift.io/scc: anyuid
  creationTimestamp: null
  generateName: ruby-ex-2-
  labels:
    app: ruby-ex
    deployment: ruby-ex-2
    deploymentconfig: ruby-ex
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: ruby-ex-2
    uid: cea6bcfc-f494-11e8-ba2b-0aa0c5b29fe8
spec:
  containers:
  - image: docker-registry.default.svc:5000/abcd/ruby-ex@sha256:f5f607d0d18bd1f4b0f25fc3a8e07652c44f83f466774b46e5d87572652e0386
    imagePullPolicy: Always
    name: ruby-ex
    ports:
    - containerPort: 8080
      protocol: TCP
    resources: {}
    securityContext:
      capabilities:
        drop:
        - MKNOD
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-xmwqt
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: default-dockercfg-hskql
  nodeName: amos01-compute001.amosdemo.io
  nodeSelector:
    node-role.kubernetes.io/compute: "true"
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    seLinuxOptions:
      level: s0:c22,c19
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: default-token-xmwqt
    secret:
      defaultMode: 420
      secretName: default-token-xmwqt
status:
  phase: Pending
  qosClass: BestEffort
